/**
 *  @file   rapptune.h
 *  @brief  RAPP Compute implementation tuning config.
 *          Auto-generated by RAPP Compute performance tuner on
 *          Fri May 27 08:24:25 2016
 */

#ifndef RAPPTUNE_H
#define RAPPTUNE_H

#include "rc_impl.h" /* Implementation names */

#define rc_compiler_version 302

#define rc_bitblt_wm_copy_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_copy_bin_UNROLL                         2
#define rc_bitblt_wm_copy_bin_SCORE                          6.26e+07

#define rc_bitblt_wm_not_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_not_bin_UNROLL                          4
#define rc_bitblt_wm_not_bin_SCORE                           6.33e+07

#define rc_bitblt_wm_and_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_and_bin_UNROLL                          4
#define rc_bitblt_wm_and_bin_SCORE                           5.87e+07

#define rc_bitblt_wm_or_bin_IMPL                             RC_IMPL_GEN
#define rc_bitblt_wm_or_bin_UNROLL                           1
#define rc_bitblt_wm_or_bin_SCORE                            5.88e+07

#define rc_bitblt_wm_xor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_xor_bin_UNROLL                          1
#define rc_bitblt_wm_xor_bin_SCORE                           6.04e+07

#define rc_bitblt_wm_nand_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_nand_bin_UNROLL                         1
#define rc_bitblt_wm_nand_bin_SCORE                          5.87e+07

#define rc_bitblt_wm_nor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_nor_bin_UNROLL                          1
#define rc_bitblt_wm_nor_bin_SCORE                           5.88e+07

#define rc_bitblt_wm_xnor_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_xnor_bin_UNROLL                         1
#define rc_bitblt_wm_xnor_bin_SCORE                          5.82e+07

#define rc_bitblt_wm_andn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_andn_bin_UNROLL                         4
#define rc_bitblt_wm_andn_bin_SCORE                          5.80e+07

#define rc_bitblt_wm_orn_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_orn_bin_UNROLL                          1
#define rc_bitblt_wm_orn_bin_SCORE                           5.84e+07

#define rc_bitblt_wm_nandn_bin_IMPL                          RC_IMPL_GEN
#define rc_bitblt_wm_nandn_bin_UNROLL                        4
#define rc_bitblt_wm_nandn_bin_SCORE                         5.78e+07

#define rc_bitblt_wm_norn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_norn_bin_UNROLL                         1
#define rc_bitblt_wm_norn_bin_SCORE                          5.84e+07

#define rc_bitblt_wa_copy_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_wa_copy_bin_UNROLL                         1
#define rc_bitblt_wa_copy_bin_SCORE                          1.18e+08

#define rc_bitblt_wa_not_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_not_bin_UNROLL                          4
#define rc_bitblt_wa_not_bin_SCORE                           7.32e+07

#define rc_bitblt_wa_and_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_and_bin_UNROLL                          4
#define rc_bitblt_wa_and_bin_SCORE                           6.89e+07

#define rc_bitblt_wa_or_bin_IMPL                             RC_IMPL_GEN
#define rc_bitblt_wa_or_bin_UNROLL                           4
#define rc_bitblt_wa_or_bin_SCORE                            6.97e+07

#define rc_bitblt_wa_xor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_xor_bin_UNROLL                          1
#define rc_bitblt_wa_xor_bin_SCORE                           6.65e+07

#define rc_bitblt_wa_nand_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_nand_bin_UNROLL                         4
#define rc_bitblt_wa_nand_bin_SCORE                          6.79e+07

#define rc_bitblt_wa_nor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_nor_bin_UNROLL                          2
#define rc_bitblt_wa_nor_bin_SCORE                           6.61e+07

#define rc_bitblt_wa_xnor_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_xnor_bin_UNROLL                         1
#define rc_bitblt_wa_xnor_bin_SCORE                          6.48e+07

#define rc_bitblt_wa_andn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_andn_bin_UNROLL                         4
#define rc_bitblt_wa_andn_bin_SCORE                          6.63e+07

#define rc_bitblt_wa_orn_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_orn_bin_UNROLL                          1
#define rc_bitblt_wa_orn_bin_SCORE                           6.61e+07

#define rc_bitblt_wa_nandn_bin_IMPL                          RC_IMPL_GEN
#define rc_bitblt_wa_nandn_bin_UNROLL                        4
#define rc_bitblt_wa_nandn_bin_SCORE                         6.81e+07

#define rc_bitblt_wa_norn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_norn_bin_UNROLL                         4
#define rc_bitblt_wa_norn_bin_SCORE                          6.82e+07

#define rc_bitblt_vm_copy_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_vm_copy_bin_UNROLL                         1
#define rc_bitblt_vm_copy_bin_SCORE                          6.94e+07

#define rc_bitblt_vm_not_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_vm_not_bin_UNROLL                          4
#define rc_bitblt_vm_not_bin_SCORE                           7.02e+07

#define rc_bitblt_vm_and_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_vm_and_bin_UNROLL                          1
#define rc_bitblt_vm_and_bin_SCORE                           5.92e+07

#define rc_bitblt_vm_or_bin_IMPL                             RC_IMPL_SWAR
#define rc_bitblt_vm_or_bin_UNROLL                           1
#define rc_bitblt_vm_or_bin_SCORE                            5.92e+07

#define rc_bitblt_vm_xor_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_vm_xor_bin_UNROLL                          1
#define rc_bitblt_vm_xor_bin_SCORE                           5.92e+07

#define rc_bitblt_vm_nand_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_vm_nand_bin_UNROLL                         1
#define rc_bitblt_vm_nand_bin_SCORE                          5.85e+07

#define rc_bitblt_vm_nor_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_vm_nor_bin_UNROLL                          1
#define rc_bitblt_vm_nor_bin_SCORE                           5.88e+07

#define rc_bitblt_vm_xnor_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_vm_xnor_bin_UNROLL                         1
#define rc_bitblt_vm_xnor_bin_SCORE                          5.87e+07

#define rc_bitblt_vm_andn_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_vm_andn_bin_UNROLL                         4
#define rc_bitblt_vm_andn_bin_SCORE                          5.92e+07

#define rc_bitblt_vm_orn_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_vm_orn_bin_UNROLL                          1
#define rc_bitblt_vm_orn_bin_SCORE                           5.90e+07

#define rc_bitblt_vm_nandn_bin_IMPL                          RC_IMPL_SWAR
#define rc_bitblt_vm_nandn_bin_UNROLL                        1
#define rc_bitblt_vm_nandn_bin_SCORE                         5.76e+07

#define rc_bitblt_vm_norn_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_vm_norn_bin_UNROLL                         1
#define rc_bitblt_vm_norn_bin_SCORE                          5.82e+07

#define rc_bitblt_va_copy_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_va_copy_bin_UNROLL                         2
#define rc_bitblt_va_copy_bin_SCORE                          7.52e+07

#define rc_bitblt_va_not_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_va_not_bin_UNROLL                          2
#define rc_bitblt_va_not_bin_SCORE                           7.34e+07

#define rc_bitblt_va_and_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_va_and_bin_UNROLL                          4
#define rc_bitblt_va_and_bin_SCORE                           6.72e+07

#define rc_bitblt_va_or_bin_IMPL                             RC_IMPL_SWAR
#define rc_bitblt_va_or_bin_UNROLL                           1
#define rc_bitblt_va_or_bin_SCORE                            6.88e+07

#define rc_bitblt_va_xor_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_va_xor_bin_UNROLL                          2
#define rc_bitblt_va_xor_bin_SCORE                           6.72e+07

#define rc_bitblt_va_nand_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_va_nand_bin_UNROLL                         1
#define rc_bitblt_va_nand_bin_SCORE                          6.75e+07

#define rc_bitblt_va_nor_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_va_nor_bin_UNROLL                          1
#define rc_bitblt_va_nor_bin_SCORE                           6.75e+07

#define rc_bitblt_va_xnor_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_va_xnor_bin_UNROLL                         4
#define rc_bitblt_va_xnor_bin_SCORE                          6.67e+07

#define rc_bitblt_va_andn_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_va_andn_bin_UNROLL                         2
#define rc_bitblt_va_andn_bin_SCORE                          6.61e+07

#define rc_bitblt_va_orn_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_va_orn_bin_UNROLL                          1
#define rc_bitblt_va_orn_bin_SCORE                           6.66e+07

#define rc_bitblt_va_nandn_bin_IMPL                          RC_IMPL_SWAR
#define rc_bitblt_va_nandn_bin_UNROLL                        1
#define rc_bitblt_va_nandn_bin_SCORE                         6.77e+07

#define rc_bitblt_va_norn_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_va_norn_bin_UNROLL                         1
#define rc_bitblt_va_norn_bin_SCORE                          6.65e+07

#define rc_pixop_set_u8_IMPL                                 RC_IMPL_GEN
#define rc_pixop_set_u8_UNROLL                               1
#define rc_pixop_set_u8_SCORE                                4.59e+07

#define rc_pixop_not_u8_IMPL                                 RC_IMPL_SWAR
#define rc_pixop_not_u8_UNROLL                               4
#define rc_pixop_not_u8_SCORE                                2.96e+07

#define rc_pixop_flip_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_flip_u8_UNROLL                              4
#define rc_pixop_flip_u8_SCORE                               2.86e+07

#define rc_pixop_lut_u8_IMPL                                 RC_IMPL_GEN
#define rc_pixop_lut_u8_UNROLL                               2
#define rc_pixop_lut_u8_SCORE                                7.76e+06

#define rc_pixop_abs_u8_IMPL                                 RC_IMPL_SWAR
#define rc_pixop_abs_u8_UNROLL                               2
#define rc_pixop_abs_u8_SCORE                                1.05e+07

#define rc_pixop_addc_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_addc_u8_UNROLL                              2
#define rc_pixop_addc_u8_SCORE                               1.21e+07

#define rc_pixop_lerpc_u8_IMPL                               RC_IMPL_SWAR
#define rc_pixop_lerpc_u8_UNROLL                             1
#define rc_pixop_lerpc_u8_SCORE                              1.56e+07

#define rc_pixop_lerpnc_u8_IMPL                              RC_IMPL_SWAR
#define rc_pixop_lerpnc_u8_UNROLL                            1
#define rc_pixop_lerpnc_u8_SCORE                             1.06e+07

#define rc_pixop_add_u8_IMPL                                 RC_IMPL_SWAR
#define rc_pixop_add_u8_UNROLL                               2
#define rc_pixop_add_u8_SCORE                                6.23e+06

#define rc_pixop_avg_u8_IMPL                                 RC_IMPL_SWAR
#define rc_pixop_avg_u8_UNROLL                               1
#define rc_pixop_avg_u8_SCORE                                7.21e+06

#define rc_pixop_sub_u8_IMPL                                 RC_IMPL_SWAR
#define rc_pixop_sub_u8_UNROLL                               2
#define rc_pixop_sub_u8_SCORE                                6.12e+06

#define rc_pixop_subh_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_subh_u8_UNROLL                              2
#define rc_pixop_subh_u8_SCORE                               6.99e+06

#define rc_pixop_suba_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_suba_u8_UNROLL                              2
#define rc_pixop_suba_u8_SCORE                               5.57e+06

#define rc_pixop_lerp_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_lerp_u8_UNROLL                              1
#define rc_pixop_lerp_u8_SCORE                               4.92e+06

#define rc_pixop_lerpn_u8_IMPL                               RC_IMPL_SWAR
#define rc_pixop_lerpn_u8_UNROLL                             2
#define rc_pixop_lerpn_u8_SCORE                              4.48e+06

#define rc_pixop_lerpi_u8_IMPL                               RC_IMPL_SWAR
#define rc_pixop_lerpi_u8_UNROLL                             2
#define rc_pixop_lerpi_u8_SCORE                              5.13e+06

#define rc_pixop_norm_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_norm_u8_UNROLL                              4
#define rc_pixop_norm_u8_SCORE                               4.48e+06

#define rc_type_u8_to_bin_IMPL                               RC_IMPL_SWAR
#define rc_type_u8_to_bin_UNROLL                             2
#define rc_type_u8_to_bin_SCORE                              1.51e+07

#define rc_type_bin_to_u8_IMPL                               RC_IMPL_GEN
#define rc_type_bin_to_u8_UNROLL                             1
#define rc_type_bin_to_u8_SCORE                              2.05e+07

#define rc_thresh_gt_u8_IMPL                                 RC_IMPL_SWAR
#define rc_thresh_gt_u8_UNROLL                               2
#define rc_thresh_gt_u8_SCORE                                1.20e+07

#define rc_thresh_lt_u8_IMPL                                 RC_IMPL_SWAR
#define rc_thresh_lt_u8_UNROLL                               2
#define rc_thresh_lt_u8_SCORE                                1.18e+07

#define rc_thresh_gtlt_u8_IMPL                               RC_IMPL_SWAR
#define rc_thresh_gtlt_u8_UNROLL                             4
#define rc_thresh_gtlt_u8_SCORE                              9.29e+06

#define rc_thresh_ltgt_u8_IMPL                               RC_IMPL_SWAR
#define rc_thresh_ltgt_u8_UNROLL                             4
#define rc_thresh_ltgt_u8_SCORE                              9.18e+06

#define rc_thresh_gt_pixel_u8_IMPL                           RC_IMPL_SWAR
#define rc_thresh_gt_pixel_u8_UNROLL                         1
#define rc_thresh_gt_pixel_u8_SCORE                          6.34e+06

#define rc_thresh_lt_pixel_u8_IMPL                           RC_IMPL_SWAR
#define rc_thresh_lt_pixel_u8_UNROLL                         1
#define rc_thresh_lt_pixel_u8_SCORE                          6.23e+06

#define rc_thresh_gtlt_pixel_u8_IMPL                         RC_IMPL_SWAR
#define rc_thresh_gtlt_pixel_u8_UNROLL                       2
#define rc_thresh_gtlt_pixel_u8_SCORE                        4.81e+06

#define rc_thresh_ltgt_pixel_u8_IMPL                         RC_IMPL_SWAR
#define rc_thresh_ltgt_pixel_u8_UNROLL                       4
#define rc_thresh_ltgt_pixel_u8_SCORE                        4.81e+06

#define rc_stat_sum_bin_IMPL                                 RC_IMPL_GEN
#define rc_stat_sum_bin_UNROLL                               4
#define rc_stat_sum_bin_SCORE                                1.03e+08

#define rc_stat_sum_u8_IMPL                                  RC_IMPL_SWAR
#define rc_stat_sum_u8_UNROLL                                2
#define rc_stat_sum_u8_SCORE                                 2.37e+07

#define rc_stat_sum2_u8_IMPL                                 RC_IMPL_GEN
#define rc_stat_sum2_u8_UNROLL                               4
#define rc_stat_sum2_u8_SCORE                                9.72e+06

#define rc_stat_xsum_u8_IMPL                                 RC_IMPL_GEN
#define rc_stat_xsum_u8_UNROLL                               4
#define rc_stat_xsum_u8_SCORE                                2.40e+06

#define rc_stat_min_bin_IMPL                                 RC_IMPL_GEN
#define rc_stat_min_bin_UNROLL                               2
#define rc_stat_min_bin_SCORE                                4.58e+08

#define rc_stat_max_bin_IMPL                                 RC_IMPL_GEN
#define rc_stat_max_bin_UNROLL                               4
#define rc_stat_max_bin_SCORE                                4.69e+08

#define rc_stat_min_u8_IMPL                                  RC_IMPL_GEN
#define rc_stat_min_u8_UNROLL                                2
#define rc_stat_min_u8_SCORE                                 1.78e+07

#define rc_stat_max_u8_IMPL                                  RC_IMPL_SWAR
#define rc_stat_max_u8_UNROLL                                2
#define rc_stat_max_u8_SCORE                                 1.33e+07

#define rc_reduce_1x2_u8_IMPL                                RC_IMPL_SWAR
#define rc_reduce_1x2_u8_UNROLL                              4
#define rc_reduce_1x2_u8_SCORE                               1.34e+07

#define rc_reduce_2x1_u8_IMPL                                RC_IMPL_SWAR
#define rc_reduce_2x1_u8_UNROLL                              1
#define rc_reduce_2x1_u8_SCORE                               1.86e+07

#define rc_reduce_2x2_u8_IMPL                                RC_IMPL_SWAR
#define rc_reduce_2x2_u8_UNROLL                              2
#define rc_reduce_2x2_u8_SCORE                               1.58e+07

#define rc_reduce_1x2_rk1_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_1x2_rk1_bin_UNROLL                         1
#define rc_reduce_1x2_rk1_bin_SCORE                          7.78e+07

#define rc_reduce_1x2_rk2_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_1x2_rk2_bin_UNROLL                         2
#define rc_reduce_1x2_rk2_bin_SCORE                          7.77e+07

#define rc_reduce_2x1_rk1_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x1_rk1_bin_UNROLL                         4
#define rc_reduce_2x1_rk1_bin_SCORE                          1.80e+08

#define rc_reduce_2x1_rk2_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x1_rk2_bin_UNROLL                         4
#define rc_reduce_2x1_rk2_bin_SCORE                          1.81e+08

#define rc_reduce_2x2_rk1_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk1_bin_UNROLL                         2
#define rc_reduce_2x2_rk1_bin_SCORE                          1.33e+08

#define rc_reduce_2x2_rk2_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk2_bin_UNROLL                         4
#define rc_reduce_2x2_rk2_bin_SCORE                          1.08e+08

#define rc_reduce_2x2_rk3_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk3_bin_UNROLL                         4
#define rc_reduce_2x2_rk3_bin_SCORE                          1.09e+08

#define rc_reduce_2x2_rk4_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk4_bin_UNROLL                         4
#define rc_reduce_2x2_rk4_bin_SCORE                          1.33e+08

#define rc_expand_1x2_bin_IMPL                               RC_IMPL_GEN
#define rc_expand_1x2_bin_UNROLL                             4
#define rc_expand_1x2_bin_SCORE                              5.38e+07

#define rc_expand_2x1_bin_IMPL                               RC_IMPL_GEN
#define rc_expand_2x1_bin_UNROLL                             4
#define rc_expand_2x1_bin_SCORE                              8.21e+07

#define rc_expand_2x2_bin_IMPL                               RC_IMPL_GEN
#define rc_expand_2x2_bin_UNROLL                             2
#define rc_expand_2x2_bin_SCORE                              4.23e+07

#define rc_rotate_cw_u8_IMPL                                 RC_IMPL_GEN
#define rc_rotate_cw_u8_UNROLL                               4
#define rc_rotate_cw_u8_SCORE                                3.60e+06

#define rc_rotate_ccw_u8_IMPL                                RC_IMPL_GEN
#define rc_rotate_ccw_u8_UNROLL                              1
#define rc_rotate_ccw_u8_SCORE                               3.50e+06

#define rc_filter_diff_1x2_horz_u8_IMPL                      RC_IMPL_SWAR
#define rc_filter_diff_1x2_horz_u8_UNROLL                    2
#define rc_filter_diff_1x2_horz_u8_SCORE                     6.66e+06

#define rc_filter_diff_1x2_horz_abs_u8_IMPL                  RC_IMPL_SWAR
#define rc_filter_diff_1x2_horz_abs_u8_UNROLL                2
#define rc_filter_diff_1x2_horz_abs_u8_SCORE                 5.68e+06

#define rc_filter_diff_2x1_vert_u8_IMPL                      RC_IMPL_SWAR
#define rc_filter_diff_2x1_vert_u8_UNROLL                    2
#define rc_filter_diff_2x1_vert_u8_SCORE                     6.88e+06

#define rc_filter_diff_2x1_vert_abs_u8_IMPL                  RC_IMPL_SWAR
#define rc_filter_diff_2x1_vert_abs_u8_UNROLL                4
#define rc_filter_diff_2x1_vert_abs_u8_SCORE                 5.57e+06

#define rc_filter_diff_2x2_magn_u8_IMPL                      RC_IMPL_SWAR
#define rc_filter_diff_2x2_magn_u8_UNROLL                    2
#define rc_filter_diff_2x2_magn_u8_SCORE                     3.06e+06

#define rc_filter_sobel_3x3_horz_u8_IMPL                     RC_IMPL_SWAR
#define rc_filter_sobel_3x3_horz_u8_UNROLL                   1
#define rc_filter_sobel_3x3_horz_u8_SCORE                    4.15e+06

#define rc_filter_sobel_3x3_horz_abs_u8_IMPL                 RC_IMPL_SWAR
#define rc_filter_sobel_3x3_horz_abs_u8_UNROLL               1
#define rc_filter_sobel_3x3_horz_abs_u8_SCORE                4.26e+06

#define rc_filter_sobel_3x3_vert_u8_IMPL                     RC_IMPL_SWAR
#define rc_filter_sobel_3x3_vert_u8_UNROLL                   1
#define rc_filter_sobel_3x3_vert_u8_SCORE                    4.70e+06

#define rc_filter_sobel_3x3_vert_abs_u8_IMPL                 RC_IMPL_SWAR
#define rc_filter_sobel_3x3_vert_abs_u8_UNROLL               1
#define rc_filter_sobel_3x3_vert_abs_u8_SCORE                4.37e+06

#define rc_filter_sobel_3x3_magn_u8_IMPL                     RC_IMPL_SWAR
#define rc_filter_sobel_3x3_magn_u8_UNROLL                   1
#define rc_filter_sobel_3x3_magn_u8_SCORE                    2.08e+06

#define rc_filter_gauss_3x3_u8_IMPL                          RC_IMPL_SWAR
#define rc_filter_gauss_3x3_u8_UNROLL                        1
#define rc_filter_gauss_3x3_u8_SCORE                         4.15e+06

#define rc_filter_laplace_3x3_u8_IMPL                        RC_IMPL_SWAR
#define rc_filter_laplace_3x3_u8_UNROLL                      1
#define rc_filter_laplace_3x3_u8_SCORE                       3.06e+06

#define rc_filter_laplace_3x3_abs_u8_IMPL                    RC_IMPL_SWAR
#define rc_filter_laplace_3x3_abs_u8_UNROLL                  1
#define rc_filter_laplace_3x3_abs_u8_SCORE                   2.73e+06

#define rc_filter_highpass_3x3_u8_IMPL                       RC_IMPL_SWAR
#define rc_filter_highpass_3x3_u8_UNROLL                     1
#define rc_filter_highpass_3x3_u8_SCORE                      2.40e+06

#define rc_filter_highpass_3x3_abs_u8_IMPL                   RC_IMPL_SWAR
#define rc_filter_highpass_3x3_abs_u8_UNROLL                 1
#define rc_filter_highpass_3x3_abs_u8_SCORE                  2.18e+06

#define rc_morph_erode_line_1x2_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_1x2_bin_UNROLL                   4
#define rc_morph_erode_line_1x2_bin_SCORE                    5.72e+07

#define rc_morph_dilate_line_1x2_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_1x2_bin_UNROLL                  4
#define rc_morph_dilate_line_1x2_bin_SCORE                   6.41e+07

#define rc_morph_erode_line_1x3_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_1x3_bin_UNROLL                   4
#define rc_morph_erode_line_1x3_bin_SCORE                    5.02e+07

#define rc_morph_dilate_line_1x3_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_1x3_bin_UNROLL                  4
#define rc_morph_dilate_line_1x3_bin_SCORE                   5.17e+07

#define rc_morph_erode_line_1x3_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x3_p_bin_UNROLL                 4
#define rc_morph_erode_line_1x3_p_bin_SCORE                  5.21e+07

#define rc_morph_dilate_line_1x3_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x3_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x3_p_bin_SCORE                 5.21e+07

#define rc_morph_erode_line_1x5_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x5_p_bin_UNROLL                 4
#define rc_morph_erode_line_1x5_p_bin_SCORE                  5.22e+07

#define rc_morph_dilate_line_1x5_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x5_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x5_p_bin_SCORE                 5.26e+07

#define rc_morph_erode_line_1x7_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x7_p_bin_UNROLL                 4
#define rc_morph_erode_line_1x7_p_bin_SCORE                  5.21e+07

#define rc_morph_dilate_line_1x7_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x7_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x7_p_bin_SCORE                 5.18e+07

#define rc_morph_erode_line_1x9_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x9_p_bin_UNROLL                 4
#define rc_morph_erode_line_1x9_p_bin_SCORE                  5.30e+07

#define rc_morph_dilate_line_1x9_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x9_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x9_p_bin_SCORE                 5.13e+07

#define rc_morph_erode_line_1x13_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x13_p_bin_UNROLL                4
#define rc_morph_erode_line_1x13_p_bin_SCORE                 5.23e+07

#define rc_morph_dilate_line_1x13_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x13_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x13_p_bin_SCORE                5.24e+07

#define rc_morph_erode_line_1x15_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x15_p_bin_UNROLL                4
#define rc_morph_erode_line_1x15_p_bin_SCORE                 5.02e+07

#define rc_morph_dilate_line_1x15_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x15_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x15_p_bin_SCORE                5.17e+07

#define rc_morph_erode_line_1x17_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x17_p_bin_UNROLL                4
#define rc_morph_erode_line_1x17_p_bin_SCORE                 5.35e+07

#define rc_morph_dilate_line_1x17_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x17_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x17_p_bin_SCORE                5.35e+07

#define rc_morph_erode_line_1x25_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x25_p_bin_UNROLL                4
#define rc_morph_erode_line_1x25_p_bin_SCORE                 5.06e+07

#define rc_morph_dilate_line_1x25_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x25_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x25_p_bin_SCORE                5.22e+07

#define rc_morph_erode_line_1x29_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x29_p_bin_UNROLL                4
#define rc_morph_erode_line_1x29_p_bin_SCORE                 5.07e+07

#define rc_morph_dilate_line_1x29_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x29_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x29_p_bin_SCORE                5.16e+07

#define rc_morph_erode_line_1x31_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x31_p_bin_UNROLL                4
#define rc_morph_erode_line_1x31_p_bin_SCORE                 5.13e+07

#define rc_morph_dilate_line_1x31_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x31_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x31_p_bin_SCORE                5.13e+07

#define rc_morph_erode_line_2x1_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_2x1_bin_UNROLL                   2
#define rc_morph_erode_line_2x1_bin_SCORE                    6.46e+07

#define rc_morph_dilate_line_2x1_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_2x1_bin_UNROLL                  4
#define rc_morph_dilate_line_2x1_bin_SCORE                   6.96e+07

#define rc_morph_erode_line_3x1_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_3x1_bin_UNROLL                   4
#define rc_morph_erode_line_3x1_bin_SCORE                    6.06e+07

#define rc_morph_dilate_line_3x1_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_3x1_bin_UNROLL                  1
#define rc_morph_dilate_line_3x1_bin_SCORE                   6.36e+07

#define rc_morph_erode_line_3x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_3x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_3x1_p_bin_SCORE                  1.24e+08

#define rc_morph_dilate_line_3x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_3x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_3x1_p_bin_SCORE                 1.27e+08

#define rc_morph_erode_line_5x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_5x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_5x1_p_bin_SCORE                  1.30e+08

#define rc_morph_dilate_line_5x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_5x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_5x1_p_bin_SCORE                 1.32e+08

#define rc_morph_erode_line_7x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_7x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_7x1_p_bin_SCORE                  1.23e+08

#define rc_morph_dilate_line_7x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_7x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_7x1_p_bin_SCORE                 1.28e+08

#define rc_morph_erode_line_9x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_9x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_9x1_p_bin_SCORE                  1.23e+08

#define rc_morph_dilate_line_9x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_9x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_9x1_p_bin_SCORE                 1.25e+08

#define rc_morph_erode_line_13x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_13x1_p_bin_UNROLL                2
#define rc_morph_erode_line_13x1_p_bin_SCORE                 1.26e+08

#define rc_morph_dilate_line_13x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_13x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_13x1_p_bin_SCORE                1.26e+08

#define rc_morph_erode_line_15x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_15x1_p_bin_UNROLL                4
#define rc_morph_erode_line_15x1_p_bin_SCORE                 1.23e+08

#define rc_morph_dilate_line_15x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_15x1_p_bin_UNROLL               1
#define rc_morph_dilate_line_15x1_p_bin_SCORE                1.22e+08

#define rc_morph_erode_line_17x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_17x1_p_bin_UNROLL                2
#define rc_morph_erode_line_17x1_p_bin_SCORE                 1.21e+08

#define rc_morph_dilate_line_17x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_17x1_p_bin_UNROLL               1
#define rc_morph_dilate_line_17x1_p_bin_SCORE                1.20e+08

#define rc_morph_erode_line_25x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_25x1_p_bin_UNROLL                2
#define rc_morph_erode_line_25x1_p_bin_SCORE                 1.21e+08

#define rc_morph_dilate_line_25x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_25x1_p_bin_UNROLL               1
#define rc_morph_dilate_line_25x1_p_bin_SCORE                1.18e+08

#define rc_morph_erode_line_29x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_29x1_p_bin_UNROLL                4
#define rc_morph_erode_line_29x1_p_bin_SCORE                 1.27e+08

#define rc_morph_dilate_line_29x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_29x1_p_bin_UNROLL               2
#define rc_morph_dilate_line_29x1_p_bin_SCORE                1.25e+08

#define rc_morph_erode_line_31x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_31x1_p_bin_UNROLL                2
#define rc_morph_erode_line_31x1_p_bin_SCORE                 1.20e+08

#define rc_morph_dilate_line_31x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_31x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_31x1_p_bin_SCORE                1.20e+08

#define rc_morph_erode_square_2x2_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_square_2x2_bin_UNROLL                 4
#define rc_morph_erode_square_2x2_bin_SCORE                  4.66e+07

#define rc_morph_dilate_square_2x2_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_square_2x2_bin_UNROLL                4
#define rc_morph_dilate_square_2x2_bin_SCORE                 4.88e+07

#define rc_morph_erode_square_3x3_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_square_3x3_bin_UNROLL                 4
#define rc_morph_erode_square_3x3_bin_SCORE                  2.83e+07

#define rc_morph_dilate_square_3x3_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_square_3x3_bin_UNROLL                4
#define rc_morph_dilate_square_3x3_bin_SCORE                 2.74e+07

#define rc_morph_erode_square_3x3_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_square_3x3_p_bin_UNROLL               4
#define rc_morph_erode_square_3x3_p_bin_SCORE                5.67e+07

#define rc_morph_dilate_square_3x3_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_square_3x3_p_bin_UNROLL              2
#define rc_morph_dilate_square_3x3_p_bin_SCORE               5.47e+07

#define rc_morph_erode_diamond_3x3_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_diamond_3x3_bin_UNROLL                4
#define rc_morph_erode_diamond_3x3_bin_SCORE                 4.15e+07

#define rc_morph_dilate_diamond_3x3_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_diamond_3x3_bin_UNROLL               4
#define rc_morph_dilate_diamond_3x3_bin_SCORE                4.47e+07

#define rc_morph_erode_diamond_3x3_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_3x3_p_bin_UNROLL              1
#define rc_morph_erode_diamond_3x3_p_bin_SCORE               4.14e+07

#define rc_morph_dilate_diamond_3x3_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_3x3_p_bin_UNROLL             4
#define rc_morph_dilate_diamond_3x3_p_bin_SCORE              4.45e+07

#define rc_morph_erode_diamond_5x5_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_5x5_p_bin_UNROLL              4
#define rc_morph_erode_diamond_5x5_p_bin_SCORE               4.14e+07

#define rc_morph_dilate_diamond_5x5_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_5x5_p_bin_UNROLL             4
#define rc_morph_dilate_diamond_5x5_p_bin_SCORE              4.38e+07

#define rc_morph_erode_diamond_7x7_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_7x7_p_bin_UNROLL              4
#define rc_morph_erode_diamond_7x7_p_bin_SCORE               4.12e+07

#define rc_morph_dilate_diamond_7x7_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_7x7_p_bin_UNROLL             4
#define rc_morph_dilate_diamond_7x7_p_bin_SCORE              4.45e+07

#define rc_morph_erode_diamond_9x9_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_9x9_p_bin_UNROLL              4
#define rc_morph_erode_diamond_9x9_p_bin_SCORE               4.14e+07

#define rc_morph_dilate_diamond_9x9_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_9x9_p_bin_UNROLL             1
#define rc_morph_dilate_diamond_9x9_p_bin_SCORE              4.26e+07

#define rc_morph_erode_diamond_13x13_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_13x13_p_bin_UNROLL            4
#define rc_morph_erode_diamond_13x13_p_bin_SCORE             4.11e+07

#define rc_morph_dilate_diamond_13x13_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_13x13_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_13x13_p_bin_SCORE            4.43e+07

#define rc_morph_erode_diamond_15x15_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_15x15_p_bin_UNROLL            4
#define rc_morph_erode_diamond_15x15_p_bin_SCORE             4.08e+07

#define rc_morph_dilate_diamond_15x15_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_15x15_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_15x15_p_bin_SCORE            4.37e+07

#define rc_morph_erode_diamond_17x17_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_17x17_p_bin_UNROLL            4
#define rc_morph_erode_diamond_17x17_p_bin_SCORE             4.26e+07

#define rc_morph_dilate_diamond_17x17_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_17x17_p_bin_UNROLL           1
#define rc_morph_dilate_diamond_17x17_p_bin_SCORE            4.31e+07

#define rc_morph_erode_diamond_25x25_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_25x25_p_bin_UNROLL            4
#define rc_morph_erode_diamond_25x25_p_bin_SCORE             4.12e+07

#define rc_morph_dilate_diamond_25x25_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_25x25_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_25x25_p_bin_SCORE            4.35e+07

#define rc_morph_erode_diamond_29x29_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_29x29_p_bin_UNROLL            1
#define rc_morph_erode_diamond_29x29_p_bin_SCORE             4.00e+07

#define rc_morph_dilate_diamond_29x29_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_29x29_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_29x29_p_bin_SCORE            4.26e+07

#define rc_morph_erode_diamond_31x31_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_31x31_p_bin_UNROLL            4
#define rc_morph_erode_diamond_31x31_p_bin_SCORE             4.10e+07

#define rc_morph_dilate_diamond_31x31_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_31x31_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_31x31_p_bin_SCORE            4.23e+07

#define rc_morph_erode_octagon_5x5_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_octagon_5x5_p_bin_UNROLL              4
#define rc_morph_erode_octagon_5x5_p_bin_SCORE               3.17e+07

#define rc_morph_dilate_octagon_5x5_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_octagon_5x5_p_bin_UNROLL             2
#define rc_morph_dilate_octagon_5x5_p_bin_SCORE              3.11e+07

#define rc_morph_erode_octagon_7x7_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_octagon_7x7_p_bin_UNROLL              2
#define rc_morph_erode_octagon_7x7_p_bin_SCORE               3.04e+07

#define rc_morph_dilate_octagon_7x7_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_octagon_7x7_p_bin_UNROLL             2
#define rc_morph_dilate_octagon_7x7_p_bin_SCORE              3.08e+07

#define rc_morph_erode_octagon_9x9_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_octagon_9x9_p_bin_UNROLL              2
#define rc_morph_erode_octagon_9x9_p_bin_SCORE               3.11e+07

#define rc_morph_dilate_octagon_9x9_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_octagon_9x9_p_bin_UNROLL             4
#define rc_morph_dilate_octagon_9x9_p_bin_SCORE              3.11e+07

#define rc_morph_erode_octagon_13x13_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_13x13_p_bin_UNROLL            2
#define rc_morph_erode_octagon_13x13_p_bin_SCORE             3.06e+07

#define rc_morph_dilate_octagon_13x13_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_13x13_p_bin_UNROLL           1
#define rc_morph_dilate_octagon_13x13_p_bin_SCORE            3.11e+07

#define rc_morph_erode_octagon_15x15_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_15x15_p_bin_UNROLL            4
#define rc_morph_erode_octagon_15x15_p_bin_SCORE             3.14e+07

#define rc_morph_dilate_octagon_15x15_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_15x15_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_15x15_p_bin_SCORE            3.09e+07

#define rc_morph_erode_octagon_17x17_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_17x17_p_bin_UNROLL            2
#define rc_morph_erode_octagon_17x17_p_bin_SCORE             3.26e+07

#define rc_morph_dilate_octagon_17x17_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_17x17_p_bin_UNROLL           1
#define rc_morph_dilate_octagon_17x17_p_bin_SCORE            3.13e+07

#define rc_morph_erode_octagon_25x25_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_25x25_p_bin_UNROLL            2
#define rc_morph_erode_octagon_25x25_p_bin_SCORE             3.18e+07

#define rc_morph_dilate_octagon_25x25_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_25x25_p_bin_UNROLL           1
#define rc_morph_dilate_octagon_25x25_p_bin_SCORE            3.10e+07

#define rc_morph_erode_octagon_29x29_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_29x29_p_bin_UNROLL            2
#define rc_morph_erode_octagon_29x29_p_bin_SCORE             3.14e+07

#define rc_morph_dilate_octagon_29x29_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_29x29_p_bin_UNROLL           2
#define rc_morph_dilate_octagon_29x29_p_bin_SCORE            3.02e+07

#define rc_morph_erode_octagon_31x31_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_31x31_p_bin_UNROLL            2
#define rc_morph_erode_octagon_31x31_p_bin_SCORE             3.13e+07

#define rc_morph_dilate_octagon_31x31_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_31x31_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_31x31_p_bin_SCORE            3.05e+07

#define rc_morph_erode_disc_7x7_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_disc_7x7_bin_UNROLL                   2
#define rc_morph_erode_disc_7x7_bin_SCORE                    1.27e+07

#define rc_morph_dilate_disc_7x7_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_disc_7x7_bin_UNROLL                  4
#define rc_morph_dilate_disc_7x7_bin_SCORE                   1.35e+07

#define rc_morph_erode_disc_7x7_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_disc_7x7_p_bin_UNROLL                 1
#define rc_morph_erode_disc_7x7_p_bin_SCORE                  2.50e+07

#define rc_morph_dilate_disc_7x7_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_disc_7x7_p_bin_UNROLL                4
#define rc_morph_dilate_disc_7x7_p_bin_SCORE                 2.60e+07

#define rc_morph_erode_disc_9x9_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_disc_9x9_p_bin_UNROLL                 4
#define rc_morph_erode_disc_9x9_p_bin_SCORE                  2.49e+07

#define rc_morph_dilate_disc_9x9_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_disc_9x9_p_bin_UNROLL                4
#define rc_morph_dilate_disc_9x9_p_bin_SCORE                 2.56e+07

#define rc_morph_erode_disc_11x11_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_11x11_p_bin_UNROLL               4
#define rc_morph_erode_disc_11x11_p_bin_SCORE                1.57e+07

#define rc_morph_dilate_disc_11x11_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_11x11_p_bin_UNROLL              4
#define rc_morph_dilate_disc_11x11_p_bin_SCORE               1.70e+07

#define rc_morph_erode_disc_13x13_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_13x13_p_bin_UNROLL               2
#define rc_morph_erode_disc_13x13_p_bin_SCORE                1.23e+07

#define rc_morph_dilate_disc_13x13_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_13x13_p_bin_UNROLL              2
#define rc_morph_dilate_disc_13x13_p_bin_SCORE               1.29e+07

#define rc_morph_erode_disc_15x15_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_15x15_p_bin_UNROLL               1
#define rc_morph_erode_disc_15x15_p_bin_SCORE                1.28e+07

#define rc_morph_dilate_disc_15x15_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_15x15_p_bin_UNROLL              4
#define rc_morph_dilate_disc_15x15_p_bin_SCORE               1.30e+07

#define rc_morph_erode_disc_17x17_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_17x17_p_bin_UNROLL               2
#define rc_morph_erode_disc_17x17_p_bin_SCORE                1.28e+07

#define rc_morph_dilate_disc_17x17_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_17x17_p_bin_UNROLL              4
#define rc_morph_dilate_disc_17x17_p_bin_SCORE               1.26e+07

#define rc_morph_erode_disc_19x19_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_19x19_p_bin_UNROLL               4
#define rc_morph_erode_disc_19x19_p_bin_SCORE                1.28e+07

#define rc_morph_dilate_disc_19x19_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_19x19_p_bin_UNROLL              4
#define rc_morph_dilate_disc_19x19_p_bin_SCORE               1.29e+07

#define rc_morph_erode_disc_25x25_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_25x25_p_bin_UNROLL               1
#define rc_morph_erode_disc_25x25_p_bin_SCORE                8.41e+06

#define rc_morph_dilate_disc_25x25_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_25x25_p_bin_UNROLL              2
#define rc_morph_dilate_disc_25x25_p_bin_SCORE               9.07e+06

#define rc_morph_hmt_golay_l_3x3_c48_r0_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r0_bin_UNROLL           4
#define rc_morph_hmt_golay_l_3x3_c48_r0_bin_SCORE            5.32e+07

#define rc_morph_hmt_golay_l_3x3_c48_r90_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r90_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c48_r90_bin_SCORE           2.79e+07

#define rc_morph_hmt_golay_l_3x3_c48_r180_bin_IMPL           RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r180_bin_UNROLL         2
#define rc_morph_hmt_golay_l_3x3_c48_r180_bin_SCORE          5.18e+07

#define rc_morph_hmt_golay_l_3x3_c48_r270_bin_IMPL           RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r270_bin_UNROLL         4
#define rc_morph_hmt_golay_l_3x3_c48_r270_bin_SCORE          2.62e+07

#define rc_morph_hmt_golay_l_3x3_c4_r45_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r45_bin_UNROLL           4
#define rc_morph_hmt_golay_l_3x3_c4_r45_bin_SCORE            3.67e+07

#define rc_morph_hmt_golay_l_3x3_c4_r135_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r135_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c4_r135_bin_SCORE           3.77e+07

#define rc_morph_hmt_golay_l_3x3_c4_r225_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r225_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c4_r225_bin_SCORE           3.78e+07

#define rc_morph_hmt_golay_l_3x3_c4_r315_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r315_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c4_r315_bin_SCORE           3.82e+07

#define rc_morph_hmt_golay_l_3x3_c8_r45_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r45_bin_UNROLL           4
#define rc_morph_hmt_golay_l_3x3_c8_r45_bin_SCORE            3.63e+07

#define rc_morph_hmt_golay_l_3x3_c8_r135_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r135_bin_UNROLL          1
#define rc_morph_hmt_golay_l_3x3_c8_r135_bin_SCORE           3.55e+07

#define rc_morph_hmt_golay_l_3x3_c8_r225_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r225_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c8_r225_bin_SCORE           3.63e+07

#define rc_morph_hmt_golay_l_3x3_c8_r315_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r315_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c8_r315_bin_SCORE           3.57e+07

#define rc_morph_hmt_golay_e_3x3_c4_r0_bin_IMPL              RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r0_bin_UNROLL            4
#define rc_morph_hmt_golay_e_3x3_c4_r0_bin_SCORE             4.50e+07

#define rc_morph_hmt_golay_e_3x3_c4_r90_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r90_bin_UNROLL           4
#define rc_morph_hmt_golay_e_3x3_c4_r90_bin_SCORE            5.09e+07

#define rc_morph_hmt_golay_e_3x3_c4_r180_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r180_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c4_r180_bin_SCORE           4.70e+07

#define rc_morph_hmt_golay_e_3x3_c4_r270_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r270_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c4_r270_bin_SCORE           5.05e+07

#define rc_morph_hmt_golay_e_3x3_c8_r0_bin_IMPL              RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r0_bin_UNROLL            4
#define rc_morph_hmt_golay_e_3x3_c8_r0_bin_SCORE             2.98e+07

#define rc_morph_hmt_golay_e_3x3_c8_r90_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r90_bin_UNROLL           4
#define rc_morph_hmt_golay_e_3x3_c8_r90_bin_SCORE            3.51e+07

#define rc_morph_hmt_golay_e_3x3_c8_r180_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r180_bin_UNROLL          1
#define rc_morph_hmt_golay_e_3x3_c8_r180_bin_SCORE           3.22e+07

#define rc_morph_hmt_golay_e_3x3_c8_r270_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r270_bin_UNROLL          1
#define rc_morph_hmt_golay_e_3x3_c8_r270_bin_SCORE           3.46e+07

#define rc_morph_hmt_golay_e_3x3_c8_r45_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r45_bin_UNROLL           1
#define rc_morph_hmt_golay_e_3x3_c8_r45_bin_SCORE            3.24e+07

#define rc_morph_hmt_golay_e_3x3_c8_r135_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r135_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r135_bin_SCORE           3.10e+07

#define rc_morph_hmt_golay_e_3x3_c8_r225_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r225_bin_UNROLL          1
#define rc_morph_hmt_golay_e_3x3_c8_r225_bin_SCORE           3.51e+07

#define rc_morph_hmt_golay_e_3x3_c8_r315_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r315_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r315_bin_SCORE           3.11e+07

#define rc_margin_horz_bin_IMPL                              RC_IMPL_GEN
#define rc_margin_horz_bin_UNROLL                            1
#define rc_margin_horz_bin_SCORE                             1.56e+08

#define rc_margin_vert_bin_IMPL                              RC_IMPL_GEN
#define rc_margin_vert_bin_UNROLL                            4
#define rc_margin_vert_bin_SCORE                             4.16e+08

#define rc_cond_set_u8_IMPL                                  RC_IMPL_GEN
#define rc_cond_set_u8_UNROLL                                2
#define rc_cond_set_u8_SCORE                                 1.12e+08

#define rc_cond_addc_u8_IMPL                                 RC_IMPL_GEN
#define rc_cond_addc_u8_UNROLL                               1
#define rc_cond_addc_u8_SCORE                                3.67e+07

#define rc_cond_subc_u8_IMPL                                 RC_IMPL_GEN
#define rc_cond_subc_u8_UNROLL                               1
#define rc_cond_subc_u8_SCORE                                3.90e+07

#define rc_cond_copy_u8_IMPL                                 RC_IMPL_GEN
#define rc_cond_copy_u8_UNROLL                               4
#define rc_cond_copy_u8_SCORE                                8.11e+07

#define rc_cond_add_u8_IMPL                                  RC_IMPL_GEN
#define rc_cond_add_u8_UNROLL                                1
#define rc_cond_add_u8_SCORE                                 2.82e+07

#endif /* RAPPTUNE_H */
