/**
 *  @file   rapptune.h
 *  @brief  RAPP Compute implementation tuning config.
 *          Auto-generated by RAPP Compute performance tuner on
 *          Mon Mar 19 19:30:48 2012
 */

#ifndef RAPPTUNE_H
#define RAPPTUNE_H

#include "rc_impl.h" /* Implementation names */

#define rc_compiler_version 406

#define rc_bitblt_wm_copy_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_copy_bin_UNROLL                         4
#define rc_bitblt_wm_copy_bin_SCORE                          3.38e+10

#define rc_bitblt_wm_not_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_not_bin_UNROLL                          4
#define rc_bitblt_wm_not_bin_SCORE                           3.60e+10

#define rc_bitblt_wm_and_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_and_bin_UNROLL                          4
#define rc_bitblt_wm_and_bin_SCORE                           3.18e+10

#define rc_bitblt_wm_or_bin_IMPL                             RC_IMPL_GEN
#define rc_bitblt_wm_or_bin_UNROLL                           4
#define rc_bitblt_wm_or_bin_SCORE                            3.16e+10

#define rc_bitblt_wm_xor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_xor_bin_UNROLL                          4
#define rc_bitblt_wm_xor_bin_SCORE                           3.17e+10

#define rc_bitblt_wm_nand_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_nand_bin_UNROLL                         4
#define rc_bitblt_wm_nand_bin_SCORE                          3.16e+10

#define rc_bitblt_wm_nor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_nor_bin_UNROLL                          4
#define rc_bitblt_wm_nor_bin_SCORE                           3.14e+10

#define rc_bitblt_wm_xnor_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_xnor_bin_UNROLL                         4
#define rc_bitblt_wm_xnor_bin_SCORE                          2.80e+10

#define rc_bitblt_wm_andn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_andn_bin_UNROLL                         4
#define rc_bitblt_wm_andn_bin_SCORE                          3.20e+10

#define rc_bitblt_wm_orn_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_orn_bin_UNROLL                          4
#define rc_bitblt_wm_orn_bin_SCORE                           3.20e+10

#define rc_bitblt_wm_nandn_bin_IMPL                          RC_IMPL_GEN
#define rc_bitblt_wm_nandn_bin_UNROLL                        4
#define rc_bitblt_wm_nandn_bin_SCORE                         3.20e+10

#define rc_bitblt_wm_norn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_norn_bin_UNROLL                         4
#define rc_bitblt_wm_norn_bin_SCORE                          3.20e+10

#define rc_bitblt_wa_copy_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_copy_bin_UNROLL                         4
#define rc_bitblt_wa_copy_bin_SCORE                          4.59e+10

#define rc_bitblt_wa_not_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_not_bin_UNROLL                          4
#define rc_bitblt_wa_not_bin_SCORE                           6.20e+10

#define rc_bitblt_wa_and_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_and_bin_UNROLL                          4
#define rc_bitblt_wa_and_bin_SCORE                           5.72e+10

#define rc_bitblt_wa_or_bin_IMPL                             RC_IMPL_GEN
#define rc_bitblt_wa_or_bin_UNROLL                           4
#define rc_bitblt_wa_or_bin_SCORE                            5.68e+10

#define rc_bitblt_wa_xor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_xor_bin_UNROLL                          4
#define rc_bitblt_wa_xor_bin_SCORE                           5.67e+10

#define rc_bitblt_wa_nand_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_nand_bin_UNROLL                         4
#define rc_bitblt_wa_nand_bin_SCORE                          5.66e+10

#define rc_bitblt_wa_nor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_nor_bin_UNROLL                          4
#define rc_bitblt_wa_nor_bin_SCORE                           5.72e+10

#define rc_bitblt_wa_xnor_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_xnor_bin_UNROLL                         4
#define rc_bitblt_wa_xnor_bin_SCORE                          4.87e+10

#define rc_bitblt_wa_andn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_andn_bin_UNROLL                         4
#define rc_bitblt_wa_andn_bin_SCORE                          5.67e+10

#define rc_bitblt_wa_orn_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_orn_bin_UNROLL                          4
#define rc_bitblt_wa_orn_bin_SCORE                           5.66e+10

#define rc_bitblt_wa_nandn_bin_IMPL                          RC_IMPL_GEN
#define rc_bitblt_wa_nandn_bin_UNROLL                        4
#define rc_bitblt_wa_nandn_bin_SCORE                         5.72e+10

#define rc_bitblt_wa_norn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_norn_bin_UNROLL                         4
#define rc_bitblt_wa_norn_bin_SCORE                          5.69e+10

#define rc_bitblt_vm_copy_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_vm_copy_bin_UNROLL                         4
#define rc_bitblt_vm_copy_bin_SCORE                          3.39e+10

#define rc_bitblt_vm_not_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_vm_not_bin_UNROLL                          4
#define rc_bitblt_vm_not_bin_SCORE                           3.38e+10

#define rc_bitblt_vm_and_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_vm_and_bin_UNROLL                          4
#define rc_bitblt_vm_and_bin_SCORE                           3.13e+10

#define rc_bitblt_vm_or_bin_IMPL                             RC_IMPL_SWAR
#define rc_bitblt_vm_or_bin_UNROLL                           4
#define rc_bitblt_vm_or_bin_SCORE                            3.15e+10

#define rc_bitblt_vm_xor_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_vm_xor_bin_UNROLL                          4
#define rc_bitblt_vm_xor_bin_SCORE                           3.14e+10

#define rc_bitblt_vm_nand_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_vm_nand_bin_UNROLL                         4
#define rc_bitblt_vm_nand_bin_SCORE                          3.13e+10

#define rc_bitblt_vm_nor_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_vm_nor_bin_UNROLL                          4
#define rc_bitblt_vm_nor_bin_SCORE                           3.16e+10

#define rc_bitblt_vm_xnor_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_vm_xnor_bin_UNROLL                         4
#define rc_bitblt_vm_xnor_bin_SCORE                          3.07e+10

#define rc_bitblt_vm_andn_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_vm_andn_bin_UNROLL                         4
#define rc_bitblt_vm_andn_bin_SCORE                          3.10e+10

#define rc_bitblt_vm_orn_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_vm_orn_bin_UNROLL                          4
#define rc_bitblt_vm_orn_bin_SCORE                           3.12e+10

#define rc_bitblt_vm_nandn_bin_IMPL                          RC_IMPL_SWAR
#define rc_bitblt_vm_nandn_bin_UNROLL                        4
#define rc_bitblt_vm_nandn_bin_SCORE                         3.13e+10

#define rc_bitblt_vm_norn_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_vm_norn_bin_UNROLL                         4
#define rc_bitblt_vm_norn_bin_SCORE                          3.14e+10

#define rc_bitblt_va_copy_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_va_copy_bin_UNROLL                         4
#define rc_bitblt_va_copy_bin_SCORE                          7.43e+10

#define rc_bitblt_va_not_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_va_not_bin_UNROLL                          4
#define rc_bitblt_va_not_bin_SCORE                           6.26e+10

#define rc_bitblt_va_and_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_va_and_bin_UNROLL                          4
#define rc_bitblt_va_and_bin_SCORE                           5.68e+10

#define rc_bitblt_va_or_bin_IMPL                             RC_IMPL_SWAR
#define rc_bitblt_va_or_bin_UNROLL                           4
#define rc_bitblt_va_or_bin_SCORE                            5.62e+10

#define rc_bitblt_va_xor_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_va_xor_bin_UNROLL                          4
#define rc_bitblt_va_xor_bin_SCORE                           5.86e+10

#define rc_bitblt_va_nand_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_va_nand_bin_UNROLL                         4
#define rc_bitblt_va_nand_bin_SCORE                          5.64e+10

#define rc_bitblt_va_nor_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_va_nor_bin_UNROLL                          4
#define rc_bitblt_va_nor_bin_SCORE                           5.68e+10

#define rc_bitblt_va_xnor_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_va_xnor_bin_UNROLL                         4
#define rc_bitblt_va_xnor_bin_SCORE                          4.93e+10

#define rc_bitblt_va_andn_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_va_andn_bin_UNROLL                         4
#define rc_bitblt_va_andn_bin_SCORE                          5.65e+10

#define rc_bitblt_va_orn_bin_IMPL                            RC_IMPL_SWAR
#define rc_bitblt_va_orn_bin_UNROLL                          4
#define rc_bitblt_va_orn_bin_SCORE                           5.67e+10

#define rc_bitblt_va_nandn_bin_IMPL                          RC_IMPL_SWAR
#define rc_bitblt_va_nandn_bin_UNROLL                        4
#define rc_bitblt_va_nandn_bin_SCORE                         5.61e+10

#define rc_bitblt_va_norn_bin_IMPL                           RC_IMPL_SWAR
#define rc_bitblt_va_norn_bin_UNROLL                         4
#define rc_bitblt_va_norn_bin_SCORE                          5.84e+10

#define rc_pixop_set_u8_IMPL                                 RC_IMPL_GEN
#define rc_pixop_set_u8_UNROLL                               1
#define rc_pixop_set_u8_SCORE                                3.92e+10

#define rc_pixop_not_u8_IMPL                                 RC_IMPL_SWAR
#define rc_pixop_not_u8_UNROLL                               4
#define rc_pixop_not_u8_SCORE                                1.12e+10

#define rc_pixop_flip_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_flip_u8_UNROLL                              4
#define rc_pixop_flip_u8_SCORE                               9.02e+09

#define rc_pixop_lut_u8_IMPL                                 RC_IMPL_GEN
#define rc_pixop_lut_u8_UNROLL                               4
#define rc_pixop_lut_u8_SCORE                                2.29e+09

#define rc_pixop_abs_u8_IMPL                                 RC_IMPL_GEN
#define rc_pixop_abs_u8_UNROLL                               1
#define rc_pixop_abs_u8_SCORE                                2.09e+09

#define rc_pixop_addc_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_addc_u8_UNROLL                              4
#define rc_pixop_addc_u8_SCORE                               2.48e+09

#define rc_pixop_lerpc_u8_IMPL                               RC_IMPL_SWAR
#define rc_pixop_lerpc_u8_UNROLL                             4
#define rc_pixop_lerpc_u8_SCORE                              4.46e+09

#define rc_pixop_lerpnc_u8_IMPL                              RC_IMPL_SWAR
#define rc_pixop_lerpnc_u8_UNROLL                            4
#define rc_pixop_lerpnc_u8_SCORE                             2.52e+09

#define rc_pixop_add_u8_IMPL                                 RC_IMPL_SWAR
#define rc_pixop_add_u8_UNROLL                               1
#define rc_pixop_add_u8_SCORE                                1.91e+09

#define rc_pixop_avg_u8_IMPL                                 RC_IMPL_SWAR
#define rc_pixop_avg_u8_UNROLL                               4
#define rc_pixop_avg_u8_SCORE                                3.58e+09

#define rc_pixop_sub_u8_IMPL                                 RC_IMPL_SWAR
#define rc_pixop_sub_u8_UNROLL                               4
#define rc_pixop_sub_u8_SCORE                                1.80e+09

#define rc_pixop_subh_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_subh_u8_UNROLL                              4
#define rc_pixop_subh_u8_SCORE                               3.20e+09

#define rc_pixop_suba_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_suba_u8_UNROLL                              2
#define rc_pixop_suba_u8_SCORE                               1.29e+09

#define rc_pixop_lerp_u8_IMPL                                RC_IMPL_SWAR
#define rc_pixop_lerp_u8_UNROLL                              1
#define rc_pixop_lerp_u8_SCORE                               1.12e+09

#define rc_pixop_lerpn_u8_IMPL                               RC_IMPL_SWAR
#define rc_pixop_lerpn_u8_UNROLL                             1
#define rc_pixop_lerpn_u8_SCORE                              9.64e+08

#define rc_pixop_lerpi_u8_IMPL                               RC_IMPL_SWAR
#define rc_pixop_lerpi_u8_UNROLL                             4
#define rc_pixop_lerpi_u8_SCORE                              1.04e+09

#define rc_pixop_norm_u8_IMPL                                RC_IMPL_GEN
#define rc_pixop_norm_u8_UNROLL                              2
#define rc_pixop_norm_u8_SCORE                               9.64e+08

#define rc_type_u8_to_bin_IMPL                               RC_IMPL_SWAR
#define rc_type_u8_to_bin_UNROLL                             4
#define rc_type_u8_to_bin_SCORE                              4.02e+09

#define rc_type_bin_to_u8_IMPL                               RC_IMPL_GEN
#define rc_type_bin_to_u8_UNROLL                             4
#define rc_type_bin_to_u8_SCORE                              1.10e+10

#define rc_thresh_gt_u8_IMPL                                 RC_IMPL_SWAR
#define rc_thresh_gt_u8_UNROLL                               1
#define rc_thresh_gt_u8_SCORE                                2.76e+09

#define rc_thresh_lt_u8_IMPL                                 RC_IMPL_SWAR
#define rc_thresh_lt_u8_UNROLL                               2
#define rc_thresh_lt_u8_SCORE                                2.69e+09

#define rc_thresh_gtlt_u8_IMPL                               RC_IMPL_SWAR
#define rc_thresh_gtlt_u8_UNROLL                             1
#define rc_thresh_gtlt_u8_SCORE                              1.92e+09

#define rc_thresh_ltgt_u8_IMPL                               RC_IMPL_SWAR
#define rc_thresh_ltgt_u8_UNROLL                             1
#define rc_thresh_ltgt_u8_SCORE                              1.96e+09

#define rc_stat_sum_bin_IMPL                                 RC_IMPL_GEN
#define rc_stat_sum_bin_UNROLL                               4
#define rc_stat_sum_bin_SCORE                                1.96e+10

#define rc_stat_sum_u8_IMPL                                  RC_IMPL_SWAR
#define rc_stat_sum_u8_UNROLL                                1
#define rc_stat_sum_u8_SCORE                                 5.52e+09

#define rc_stat_sum2_u8_IMPL                                 RC_IMPL_GEN
#define rc_stat_sum2_u8_UNROLL                               4
#define rc_stat_sum2_u8_SCORE                                1.93e+09

#define rc_stat_xsum_u8_IMPL                                 RC_IMPL_GEN
#define rc_stat_xsum_u8_UNROLL                               1
#define rc_stat_xsum_u8_SCORE                                5.85e+08

#define rc_stat_min_bin_IMPL                                 RC_IMPL_GEN
#define rc_stat_min_bin_UNROLL                               2
#define rc_stat_min_bin_SCORE                                8.19e+10

#define rc_stat_max_bin_IMPL                                 RC_IMPL_SWAR
#define rc_stat_max_bin_UNROLL                               2
#define rc_stat_max_bin_SCORE                                8.41e+10

#define rc_stat_min_u8_IMPL                                  RC_IMPL_GEN
#define rc_stat_min_u8_UNROLL                                4
#define rc_stat_min_u8_SCORE                                 1.20e+09

#define rc_stat_max_u8_IMPL                                  RC_IMPL_GEN
#define rc_stat_max_u8_UNROLL                                4
#define rc_stat_max_u8_SCORE                                 1.11e+09

#define rc_reduce_1x2_u8_IMPL                                RC_IMPL_GEN
#define rc_reduce_1x2_u8_UNROLL                              4
#define rc_reduce_1x2_u8_SCORE                               2.99e+09

#define rc_reduce_2x1_u8_IMPL                                RC_IMPL_SWAR
#define rc_reduce_2x1_u8_UNROLL                              4
#define rc_reduce_2x1_u8_SCORE                               8.21e+09

#define rc_reduce_2x2_u8_IMPL                                RC_IMPL_GEN
#define rc_reduce_2x2_u8_UNROLL                              4
#define rc_reduce_2x2_u8_SCORE                               3.49e+09

#define rc_reduce_1x2_rk1_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_1x2_rk1_bin_UNROLL                         4
#define rc_reduce_1x2_rk1_bin_SCORE                          1.65e+10

#define rc_reduce_1x2_rk2_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_1x2_rk2_bin_UNROLL                         4
#define rc_reduce_1x2_rk2_bin_SCORE                          1.74e+10

#define rc_reduce_2x1_rk1_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x1_rk1_bin_UNROLL                         4
#define rc_reduce_2x1_rk1_bin_SCORE                          1.07e+11

#define rc_reduce_2x1_rk2_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x1_rk2_bin_UNROLL                         4
#define rc_reduce_2x1_rk2_bin_SCORE                          1.08e+11

#define rc_reduce_2x2_rk1_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk1_bin_UNROLL                         4
#define rc_reduce_2x2_rk1_bin_SCORE                          2.68e+10

#define rc_reduce_2x2_rk2_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk2_bin_UNROLL                         4
#define rc_reduce_2x2_rk2_bin_SCORE                          2.19e+10

#define rc_reduce_2x2_rk3_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk3_bin_UNROLL                         2
#define rc_reduce_2x2_rk3_bin_SCORE                          2.19e+10

#define rc_reduce_2x2_rk4_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk4_bin_UNROLL                         4
#define rc_reduce_2x2_rk4_bin_SCORE                          2.76e+10

#define rc_expand_1x2_bin_IMPL                               RC_IMPL_GEN
#define rc_expand_1x2_bin_UNROLL                             1
#define rc_expand_1x2_bin_SCORE                              1.44e+10

#define rc_expand_2x1_bin_IMPL                               RC_IMPL_GEN
#define rc_expand_2x1_bin_UNROLL                             4
#define rc_expand_2x1_bin_SCORE                              4.99e+10

#define rc_expand_2x2_bin_IMPL                               RC_IMPL_GEN
#define rc_expand_2x2_bin_UNROLL                             4
#define rc_expand_2x2_bin_SCORE                              1.35e+10

#define rc_rotate_cw_u8_IMPL                                 RC_IMPL_GEN
#define rc_rotate_cw_u8_UNROLL                               4
#define rc_rotate_cw_u8_SCORE                                1.57e+09

#define rc_rotate_ccw_u8_IMPL                                RC_IMPL_GEN
#define rc_rotate_ccw_u8_UNROLL                              4
#define rc_rotate_ccw_u8_SCORE                               1.57e+09

#define rc_filter_diff_1x2_horz_u8_IMPL                      RC_IMPL_SWAR
#define rc_filter_diff_1x2_horz_u8_UNROLL                    2
#define rc_filter_diff_1x2_horz_u8_SCORE                     2.27e+09

#define rc_filter_diff_1x2_horz_abs_u8_IMPL                  RC_IMPL_SWAR
#define rc_filter_diff_1x2_horz_abs_u8_UNROLL                4
#define rc_filter_diff_1x2_horz_abs_u8_SCORE                 1.05e+09

#define rc_filter_diff_2x1_vert_u8_IMPL                      RC_IMPL_SWAR
#define rc_filter_diff_2x1_vert_u8_UNROLL                    4
#define rc_filter_diff_2x1_vert_u8_SCORE                     3.28e+09

#define rc_filter_diff_2x1_vert_abs_u8_IMPL                  RC_IMPL_SWAR
#define rc_filter_diff_2x1_vert_abs_u8_UNROLL                1
#define rc_filter_diff_2x1_vert_abs_u8_SCORE                 1.36e+09

#define rc_filter_diff_2x2_magn_u8_IMPL                      RC_IMPL_SWAR
#define rc_filter_diff_2x2_magn_u8_UNROLL                    4
#define rc_filter_diff_2x2_magn_u8_SCORE                     6.42e+08

#define rc_filter_sobel_3x3_horz_u8_IMPL                     RC_IMPL_SWAR
#define rc_filter_sobel_3x3_horz_u8_UNROLL                   1
#define rc_filter_sobel_3x3_horz_u8_SCORE                    9.43e+08

#define rc_filter_sobel_3x3_horz_abs_u8_IMPL                 RC_IMPL_SWAR
#define rc_filter_sobel_3x3_horz_abs_u8_UNROLL               1
#define rc_filter_sobel_3x3_horz_abs_u8_SCORE                6.20e+08

#define rc_filter_sobel_3x3_vert_u8_IMPL                     RC_IMPL_SWAR
#define rc_filter_sobel_3x3_vert_u8_UNROLL                   1
#define rc_filter_sobel_3x3_vert_u8_SCORE                    9.32e+08

#define rc_filter_sobel_3x3_vert_abs_u8_IMPL                 RC_IMPL_SWAR
#define rc_filter_sobel_3x3_vert_abs_u8_UNROLL               1
#define rc_filter_sobel_3x3_vert_abs_u8_SCORE                6.11e+08

#define rc_filter_sobel_3x3_magn_u8_IMPL                     RC_IMPL_SWAR
#define rc_filter_sobel_3x3_magn_u8_UNROLL                   1
#define rc_filter_sobel_3x3_magn_u8_SCORE                    3.59e+08

#define rc_filter_gauss_3x3_u8_IMPL                          RC_IMPL_SWAR
#define rc_filter_gauss_3x3_u8_UNROLL                        1
#define rc_filter_gauss_3x3_u8_SCORE                         7.59e+08

#define rc_filter_laplace_3x3_u8_IMPL                        RC_IMPL_SWAR
#define rc_filter_laplace_3x3_u8_UNROLL                      1
#define rc_filter_laplace_3x3_u8_SCORE                       8.74e+08

#define rc_filter_laplace_3x3_abs_u8_IMPL                    RC_IMPL_SWAR
#define rc_filter_laplace_3x3_abs_u8_UNROLL                  1
#define rc_filter_laplace_3x3_abs_u8_SCORE                   5.64e+08

#define rc_filter_highpass_3x3_u8_IMPL                       RC_IMPL_GEN
#define rc_filter_highpass_3x3_u8_UNROLL                     1
#define rc_filter_highpass_3x3_u8_SCORE                      5.14e+08

#define rc_filter_highpass_3x3_abs_u8_IMPL                   RC_IMPL_GEN
#define rc_filter_highpass_3x3_abs_u8_UNROLL                 1
#define rc_filter_highpass_3x3_abs_u8_SCORE                  3.96e+08

#define rc_morph_erode_line_1x2_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_1x2_bin_UNROLL                   4
#define rc_morph_erode_line_1x2_bin_SCORE                    1.44e+10

#define rc_morph_dilate_line_1x2_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_1x2_bin_UNROLL                  4
#define rc_morph_dilate_line_1x2_bin_SCORE                   3.28e+10

#define rc_morph_erode_line_1x3_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_1x3_bin_UNROLL                   1
#define rc_morph_erode_line_1x3_bin_SCORE                    9.20e+09

#define rc_morph_dilate_line_1x3_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_1x3_bin_UNROLL                  1
#define rc_morph_dilate_line_1x3_bin_SCORE                   8.67e+09

#define rc_morph_erode_line_1x3_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x3_p_bin_UNROLL                 1
#define rc_morph_erode_line_1x3_p_bin_SCORE                  1.00e+10

#define rc_morph_dilate_line_1x3_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x3_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x3_p_bin_SCORE                 1.02e+10

#define rc_morph_erode_line_1x5_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x5_p_bin_UNROLL                 1
#define rc_morph_erode_line_1x5_p_bin_SCORE                  1.01e+10

#define rc_morph_dilate_line_1x5_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x5_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x5_p_bin_SCORE                 1.04e+10

#define rc_morph_erode_line_1x7_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x7_p_bin_UNROLL                 1
#define rc_morph_erode_line_1x7_p_bin_SCORE                  1.02e+10

#define rc_morph_dilate_line_1x7_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x7_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x7_p_bin_SCORE                 1.02e+10

#define rc_morph_erode_line_1x9_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x9_p_bin_UNROLL                 1
#define rc_morph_erode_line_1x9_p_bin_SCORE                  9.97e+09

#define rc_morph_dilate_line_1x9_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x9_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x9_p_bin_SCORE                 1.03e+10

#define rc_morph_erode_line_1x13_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x13_p_bin_UNROLL                1
#define rc_morph_erode_line_1x13_p_bin_SCORE                 9.89e+09

#define rc_morph_dilate_line_1x13_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x13_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x13_p_bin_SCORE                1.03e+10

#define rc_morph_erode_line_1x15_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x15_p_bin_UNROLL                1
#define rc_morph_erode_line_1x15_p_bin_SCORE                 1.01e+10

#define rc_morph_dilate_line_1x15_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x15_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x15_p_bin_SCORE                1.03e+10

#define rc_morph_erode_line_1x17_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x17_p_bin_UNROLL                4
#define rc_morph_erode_line_1x17_p_bin_SCORE                 1.20e+10

#define rc_morph_dilate_line_1x17_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x17_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x17_p_bin_SCORE                1.08e+10

#define rc_morph_erode_line_1x25_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x25_p_bin_UNROLL                1
#define rc_morph_erode_line_1x25_p_bin_SCORE                 1.01e+10

#define rc_morph_dilate_line_1x25_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x25_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x25_p_bin_SCORE                1.01e+10

#define rc_morph_erode_line_1x29_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x29_p_bin_UNROLL                1
#define rc_morph_erode_line_1x29_p_bin_SCORE                 1.00e+10

#define rc_morph_dilate_line_1x29_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x29_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x29_p_bin_SCORE                1.02e+10

#define rc_morph_erode_line_1x31_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x31_p_bin_UNROLL                1
#define rc_morph_erode_line_1x31_p_bin_SCORE                 1.01e+10

#define rc_morph_dilate_line_1x31_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x31_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x31_p_bin_SCORE                1.04e+10

#define rc_morph_erode_line_2x1_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_2x1_bin_UNROLL                   4
#define rc_morph_erode_line_2x1_bin_SCORE                    5.32e+10

#define rc_morph_dilate_line_2x1_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_2x1_bin_UNROLL                  4
#define rc_morph_dilate_line_2x1_bin_SCORE                   5.42e+10

#define rc_morph_erode_line_3x1_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_3x1_bin_UNROLL                   4
#define rc_morph_erode_line_3x1_bin_SCORE                    3.87e+10

#define rc_morph_dilate_line_3x1_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_3x1_bin_UNROLL                  4
#define rc_morph_dilate_line_3x1_bin_SCORE                   3.87e+10

#define rc_morph_erode_line_3x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_3x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_3x1_p_bin_SCORE                  5.98e+10

#define rc_morph_dilate_line_3x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_3x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_3x1_p_bin_SCORE                 5.92e+10

#define rc_morph_erode_line_5x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_5x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_5x1_p_bin_SCORE                  5.91e+10

#define rc_morph_dilate_line_5x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_5x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_5x1_p_bin_SCORE                 5.65e+10

#define rc_morph_erode_line_7x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_7x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_7x1_p_bin_SCORE                  5.87e+10

#define rc_morph_dilate_line_7x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_7x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_7x1_p_bin_SCORE                 5.85e+10

#define rc_morph_erode_line_9x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_9x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_9x1_p_bin_SCORE                  5.68e+10

#define rc_morph_dilate_line_9x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_9x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_9x1_p_bin_SCORE                 5.90e+10

#define rc_morph_erode_line_13x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_13x1_p_bin_UNROLL                4
#define rc_morph_erode_line_13x1_p_bin_SCORE                 5.86e+10

#define rc_morph_dilate_line_13x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_13x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_13x1_p_bin_SCORE                5.90e+10

#define rc_morph_erode_line_15x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_15x1_p_bin_UNROLL                4
#define rc_morph_erode_line_15x1_p_bin_SCORE                 5.73e+10

#define rc_morph_dilate_line_15x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_15x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_15x1_p_bin_SCORE                5.66e+10

#define rc_morph_erode_line_17x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_17x1_p_bin_UNROLL                4
#define rc_morph_erode_line_17x1_p_bin_SCORE                 5.95e+10

#define rc_morph_dilate_line_17x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_17x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_17x1_p_bin_SCORE                5.76e+10

#define rc_morph_erode_line_25x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_25x1_p_bin_UNROLL                4
#define rc_morph_erode_line_25x1_p_bin_SCORE                 5.66e+10

#define rc_morph_dilate_line_25x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_25x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_25x1_p_bin_SCORE                5.76e+10

#define rc_morph_erode_line_29x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_29x1_p_bin_UNROLL                4
#define rc_morph_erode_line_29x1_p_bin_SCORE                 5.68e+10

#define rc_morph_dilate_line_29x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_29x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_29x1_p_bin_SCORE                5.74e+10

#define rc_morph_erode_line_31x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_31x1_p_bin_UNROLL                4
#define rc_morph_erode_line_31x1_p_bin_SCORE                 5.84e+10

#define rc_morph_dilate_line_31x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_31x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_31x1_p_bin_SCORE                5.91e+10

#define rc_morph_erode_square_2x2_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_square_2x2_bin_UNROLL                 4
#define rc_morph_erode_square_2x2_bin_SCORE                  9.87e+09

#define rc_morph_dilate_square_2x2_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_square_2x2_bin_UNROLL                4
#define rc_morph_dilate_square_2x2_bin_SCORE                 1.77e+10

#define rc_morph_erode_square_3x3_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_square_3x3_bin_UNROLL                 1
#define rc_morph_erode_square_3x3_bin_SCORE                  4.78e+09

#define rc_morph_dilate_square_3x3_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_square_3x3_bin_UNROLL                2
#define rc_morph_dilate_square_3x3_bin_SCORE                 4.02e+09

#define rc_morph_erode_square_3x3_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_square_3x3_p_bin_UNROLL               4
#define rc_morph_erode_square_3x3_p_bin_SCORE                1.27e+10

#define rc_morph_dilate_square_3x3_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_square_3x3_p_bin_UNROLL              4
#define rc_morph_dilate_square_3x3_p_bin_SCORE               1.20e+10

#define rc_morph_erode_diamond_3x3_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_diamond_3x3_bin_UNROLL                2
#define rc_morph_erode_diamond_3x3_bin_SCORE                 8.27e+09

#define rc_morph_dilate_diamond_3x3_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_diamond_3x3_bin_UNROLL               1
#define rc_morph_dilate_diamond_3x3_bin_SCORE                8.14e+09

#define rc_morph_erode_diamond_3x3_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_3x3_p_bin_UNROLL              4
#define rc_morph_erode_diamond_3x3_p_bin_SCORE               9.26e+09

#define rc_morph_dilate_diamond_3x3_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_3x3_p_bin_UNROLL             4
#define rc_morph_dilate_diamond_3x3_p_bin_SCORE              8.51e+09

#define rc_morph_erode_diamond_5x5_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_5x5_p_bin_UNROLL              4
#define rc_morph_erode_diamond_5x5_p_bin_SCORE               9.72e+09

#define rc_morph_dilate_diamond_5x5_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_5x5_p_bin_UNROLL             4
#define rc_morph_dilate_diamond_5x5_p_bin_SCORE              8.50e+09

#define rc_morph_erode_diamond_7x7_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_7x7_p_bin_UNROLL              4
#define rc_morph_erode_diamond_7x7_p_bin_SCORE               9.20e+09

#define rc_morph_dilate_diamond_7x7_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_7x7_p_bin_UNROLL             1
#define rc_morph_dilate_diamond_7x7_p_bin_SCORE              8.30e+09

#define rc_morph_erode_diamond_9x9_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_9x9_p_bin_UNROLL              4
#define rc_morph_erode_diamond_9x9_p_bin_SCORE               9.09e+09

#define rc_morph_dilate_diamond_9x9_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_9x9_p_bin_UNROLL             4
#define rc_morph_dilate_diamond_9x9_p_bin_SCORE              8.43e+09

#define rc_morph_erode_diamond_13x13_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_13x13_p_bin_UNROLL            4
#define rc_morph_erode_diamond_13x13_p_bin_SCORE             9.72e+09

#define rc_morph_dilate_diamond_13x13_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_13x13_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_13x13_p_bin_SCORE            8.44e+09

#define rc_morph_erode_diamond_15x15_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_15x15_p_bin_UNROLL            2
#define rc_morph_erode_diamond_15x15_p_bin_SCORE             8.58e+09

#define rc_morph_dilate_diamond_15x15_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_15x15_p_bin_UNROLL           1
#define rc_morph_dilate_diamond_15x15_p_bin_SCORE            8.39e+09

#define rc_morph_erode_diamond_17x17_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_17x17_p_bin_UNROLL            4
#define rc_morph_erode_diamond_17x17_p_bin_SCORE             9.88e+09

#define rc_morph_dilate_diamond_17x17_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_17x17_p_bin_UNROLL           1
#define rc_morph_dilate_diamond_17x17_p_bin_SCORE            8.69e+09

#define rc_morph_erode_diamond_25x25_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_25x25_p_bin_UNROLL            4
#define rc_morph_erode_diamond_25x25_p_bin_SCORE             9.37e+09

#define rc_morph_dilate_diamond_25x25_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_25x25_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_25x25_p_bin_SCORE            8.48e+09

#define rc_morph_erode_diamond_29x29_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_29x29_p_bin_UNROLL            4
#define rc_morph_erode_diamond_29x29_p_bin_SCORE             9.34e+09

#define rc_morph_dilate_diamond_29x29_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_29x29_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_29x29_p_bin_SCORE            8.47e+09

#define rc_morph_erode_diamond_31x31_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_31x31_p_bin_UNROLL            4
#define rc_morph_erode_diamond_31x31_p_bin_SCORE             9.69e+09

#define rc_morph_dilate_diamond_31x31_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_31x31_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_31x31_p_bin_SCORE            8.45e+09

#define rc_morph_erode_octagon_5x5_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_octagon_5x5_p_bin_UNROLL              4
#define rc_morph_erode_octagon_5x5_p_bin_SCORE               6.26e+09

#define rc_morph_dilate_octagon_5x5_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_octagon_5x5_p_bin_UNROLL             4
#define rc_morph_dilate_octagon_5x5_p_bin_SCORE              5.44e+09

#define rc_morph_erode_octagon_7x7_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_octagon_7x7_p_bin_UNROLL              1
#define rc_morph_erode_octagon_7x7_p_bin_SCORE               6.15e+09

#define rc_morph_dilate_octagon_7x7_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_octagon_7x7_p_bin_UNROLL             4
#define rc_morph_dilate_octagon_7x7_p_bin_SCORE              5.57e+09

#define rc_morph_erode_octagon_9x9_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_octagon_9x9_p_bin_UNROLL              4
#define rc_morph_erode_octagon_9x9_p_bin_SCORE               6.30e+09

#define rc_morph_dilate_octagon_9x9_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_octagon_9x9_p_bin_UNROLL             1
#define rc_morph_dilate_octagon_9x9_p_bin_SCORE              5.58e+09

#define rc_morph_erode_octagon_13x13_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_13x13_p_bin_UNROLL            4
#define rc_morph_erode_octagon_13x13_p_bin_SCORE             6.30e+09

#define rc_morph_dilate_octagon_13x13_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_13x13_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_13x13_p_bin_SCORE            5.53e+09

#define rc_morph_erode_octagon_15x15_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_15x15_p_bin_UNROLL            4
#define rc_morph_erode_octagon_15x15_p_bin_SCORE             6.39e+09

#define rc_morph_dilate_octagon_15x15_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_15x15_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_15x15_p_bin_SCORE            5.56e+09

#define rc_morph_erode_octagon_17x17_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_17x17_p_bin_UNROLL            4
#define rc_morph_erode_octagon_17x17_p_bin_SCORE             6.67e+09

#define rc_morph_dilate_octagon_17x17_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_17x17_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_17x17_p_bin_SCORE            5.75e+09

#define rc_morph_erode_octagon_25x25_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_25x25_p_bin_UNROLL            4
#define rc_morph_erode_octagon_25x25_p_bin_SCORE             6.34e+09

#define rc_morph_dilate_octagon_25x25_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_25x25_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_25x25_p_bin_SCORE            5.56e+09

#define rc_morph_erode_octagon_29x29_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_29x29_p_bin_UNROLL            1
#define rc_morph_erode_octagon_29x29_p_bin_SCORE             6.32e+09

#define rc_morph_dilate_octagon_29x29_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_29x29_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_29x29_p_bin_SCORE            5.53e+09

#define rc_morph_erode_octagon_31x31_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_31x31_p_bin_UNROLL            1
#define rc_morph_erode_octagon_31x31_p_bin_SCORE             6.30e+09

#define rc_morph_dilate_octagon_31x31_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_31x31_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_31x31_p_bin_SCORE            5.57e+09

#define rc_morph_erode_disc_7x7_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_disc_7x7_bin_UNROLL                   1
#define rc_morph_erode_disc_7x7_bin_SCORE                    2.17e+09

#define rc_morph_dilate_disc_7x7_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_disc_7x7_bin_UNROLL                  1
#define rc_morph_dilate_disc_7x7_bin_SCORE                   1.39e+09

#define rc_morph_erode_disc_7x7_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_disc_7x7_p_bin_UNROLL                 1
#define rc_morph_erode_disc_7x7_p_bin_SCORE                  4.54e+09

#define rc_morph_dilate_disc_7x7_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_disc_7x7_p_bin_UNROLL                2
#define rc_morph_dilate_disc_7x7_p_bin_SCORE                 3.94e+09

#define rc_morph_erode_disc_9x9_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_disc_9x9_p_bin_UNROLL                 4
#define rc_morph_erode_disc_9x9_p_bin_SCORE                  4.64e+09

#define rc_morph_dilate_disc_9x9_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_disc_9x9_p_bin_UNROLL                2
#define rc_morph_dilate_disc_9x9_p_bin_SCORE                 3.98e+09

#define rc_morph_erode_disc_11x11_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_11x11_p_bin_UNROLL               1
#define rc_morph_erode_disc_11x11_p_bin_SCORE                3.03e+09

#define rc_morph_dilate_disc_11x11_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_11x11_p_bin_UNROLL              1
#define rc_morph_dilate_disc_11x11_p_bin_SCORE               2.02e+09

#define rc_morph_erode_disc_13x13_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_13x13_p_bin_UNROLL               2
#define rc_morph_erode_disc_13x13_p_bin_SCORE                2.26e+09

#define rc_morph_dilate_disc_13x13_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_13x13_p_bin_UNROLL              1
#define rc_morph_dilate_disc_13x13_p_bin_SCORE               1.88e+09

#define rc_morph_erode_disc_15x15_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_15x15_p_bin_UNROLL               2
#define rc_morph_erode_disc_15x15_p_bin_SCORE                2.22e+09

#define rc_morph_dilate_disc_15x15_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_15x15_p_bin_UNROLL              1
#define rc_morph_dilate_disc_15x15_p_bin_SCORE               1.83e+09

#define rc_morph_erode_disc_17x17_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_17x17_p_bin_UNROLL               4
#define rc_morph_erode_disc_17x17_p_bin_SCORE                2.23e+09

#define rc_morph_dilate_disc_17x17_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_17x17_p_bin_UNROLL              1
#define rc_morph_dilate_disc_17x17_p_bin_SCORE               1.92e+09

#define rc_morph_erode_disc_19x19_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_19x19_p_bin_UNROLL               4
#define rc_morph_erode_disc_19x19_p_bin_SCORE                2.16e+09

#define rc_morph_dilate_disc_19x19_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_19x19_p_bin_UNROLL              1
#define rc_morph_dilate_disc_19x19_p_bin_SCORE               1.90e+09

#define rc_morph_erode_disc_25x25_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_25x25_p_bin_UNROLL               4
#define rc_morph_erode_disc_25x25_p_bin_SCORE                1.55e+09

#define rc_morph_dilate_disc_25x25_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_25x25_p_bin_UNROLL              1
#define rc_morph_dilate_disc_25x25_p_bin_SCORE               1.38e+09

#define rc_morph_hmt_golay_l_3x3_c48_r0_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r0_bin_UNROLL           4
#define rc_morph_hmt_golay_l_3x3_c48_r0_bin_SCORE            1.15e+10

#define rc_morph_hmt_golay_l_3x3_c48_r90_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r90_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c48_r90_bin_SCORE           5.59e+09

#define rc_morph_hmt_golay_l_3x3_c48_r180_bin_IMPL           RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r180_bin_UNROLL         1
#define rc_morph_hmt_golay_l_3x3_c48_r180_bin_SCORE          1.16e+10

#define rc_morph_hmt_golay_l_3x3_c48_r270_bin_IMPL           RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r270_bin_UNROLL         4
#define rc_morph_hmt_golay_l_3x3_c48_r270_bin_SCORE          5.40e+09

#define rc_morph_hmt_golay_l_3x3_c4_r45_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r45_bin_UNROLL           2
#define rc_morph_hmt_golay_l_3x3_c4_r45_bin_SCORE            7.00e+09

#define rc_morph_hmt_golay_l_3x3_c4_r135_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r135_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c4_r135_bin_SCORE           7.44e+09

#define rc_morph_hmt_golay_l_3x3_c4_r225_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r225_bin_UNROLL          2
#define rc_morph_hmt_golay_l_3x3_c4_r225_bin_SCORE           7.34e+09

#define rc_morph_hmt_golay_l_3x3_c4_r315_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r315_bin_UNROLL          2
#define rc_morph_hmt_golay_l_3x3_c4_r315_bin_SCORE           7.25e+09

#define rc_morph_hmt_golay_l_3x3_c8_r45_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r45_bin_UNROLL           4
#define rc_morph_hmt_golay_l_3x3_c8_r45_bin_SCORE            7.39e+09

#define rc_morph_hmt_golay_l_3x3_c8_r135_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r135_bin_UNROLL          2
#define rc_morph_hmt_golay_l_3x3_c8_r135_bin_SCORE           7.36e+09

#define rc_morph_hmt_golay_l_3x3_c8_r225_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r225_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c8_r225_bin_SCORE           7.38e+09

#define rc_morph_hmt_golay_l_3x3_c8_r315_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r315_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c8_r315_bin_SCORE           7.35e+09

#define rc_morph_hmt_golay_e_3x3_c4_r0_bin_IMPL              RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r0_bin_UNROLL            4
#define rc_morph_hmt_golay_e_3x3_c4_r0_bin_SCORE             9.99e+09

#define rc_morph_hmt_golay_e_3x3_c4_r90_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r90_bin_UNROLL           4
#define rc_morph_hmt_golay_e_3x3_c4_r90_bin_SCORE            2.52e+10

#define rc_morph_hmt_golay_e_3x3_c4_r180_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r180_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c4_r180_bin_SCORE           9.76e+09

#define rc_morph_hmt_golay_e_3x3_c4_r270_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r270_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c4_r270_bin_SCORE           1.18e+10

#define rc_morph_hmt_golay_e_3x3_c8_r0_bin_IMPL              RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r0_bin_UNROLL            4
#define rc_morph_hmt_golay_e_3x3_c8_r0_bin_SCORE             5.51e+09

#define rc_morph_hmt_golay_e_3x3_c8_r90_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r90_bin_UNROLL           4
#define rc_morph_hmt_golay_e_3x3_c8_r90_bin_SCORE            9.97e+09

#define rc_morph_hmt_golay_e_3x3_c8_r180_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r180_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r180_bin_SCORE           5.13e+09

#define rc_morph_hmt_golay_e_3x3_c8_r270_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r270_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r270_bin_SCORE           5.74e+09

#define rc_morph_hmt_golay_e_3x3_c8_r45_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r45_bin_UNROLL           1
#define rc_morph_hmt_golay_e_3x3_c8_r45_bin_SCORE            5.68e+09

#define rc_morph_hmt_golay_e_3x3_c8_r135_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r135_bin_UNROLL          1
#define rc_morph_hmt_golay_e_3x3_c8_r135_bin_SCORE           5.43e+09

#define rc_morph_hmt_golay_e_3x3_c8_r225_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r225_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r225_bin_SCORE           1.01e+10

#define rc_morph_hmt_golay_e_3x3_c8_r315_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r315_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r315_bin_SCORE           5.48e+09

#define rc_margin_horz_bin_IMPL                              RC_IMPL_GEN
#define rc_margin_horz_bin_UNROLL                            4
#define rc_margin_horz_bin_SCORE                             5.43e+10

#define rc_margin_vert_bin_IMPL                              RC_IMPL_GEN
#define rc_margin_vert_bin_UNROLL                            2
#define rc_margin_vert_bin_SCORE                             7.53e+10

#endif /* RAPPTUNE_H */
