/**
 *  @file   rapptune.h
 *  @brief  RAPP Compute implementation tuning config.
 *          Auto-generated by RAPP Compute performance tuner on
 *          Fri May 27 05:02:38 2016
 */

#ifndef RAPPTUNE_H
#define RAPPTUNE_H

#include "rc_impl.h" /* Implementation names */

#define rc_compiler_version 407

#define rc_bitblt_wm_copy_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_copy_bin_UNROLL                         4
#define rc_bitblt_wm_copy_bin_SCORE                          1.95e+09

#define rc_bitblt_wm_not_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_not_bin_UNROLL                          4
#define rc_bitblt_wm_not_bin_SCORE                           1.74e+09

#define rc_bitblt_wm_and_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_and_bin_UNROLL                          4
#define rc_bitblt_wm_and_bin_SCORE                           1.38e+09

#define rc_bitblt_wm_or_bin_IMPL                             RC_IMPL_GEN
#define rc_bitblt_wm_or_bin_UNROLL                           4
#define rc_bitblt_wm_or_bin_SCORE                            1.34e+09

#define rc_bitblt_wm_xor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_xor_bin_UNROLL                          4
#define rc_bitblt_wm_xor_bin_SCORE                           1.37e+09

#define rc_bitblt_wm_nand_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_nand_bin_UNROLL                         4
#define rc_bitblt_wm_nand_bin_SCORE                          1.24e+09

#define rc_bitblt_wm_nor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_nor_bin_UNROLL                          4
#define rc_bitblt_wm_nor_bin_SCORE                           1.23e+09

#define rc_bitblt_wm_xnor_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_xnor_bin_UNROLL                         4
#define rc_bitblt_wm_xnor_bin_SCORE                          1.25e+09

#define rc_bitblt_wm_andn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_andn_bin_UNROLL                         4
#define rc_bitblt_wm_andn_bin_SCORE                          1.30e+09

#define rc_bitblt_wm_orn_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wm_orn_bin_UNROLL                          4
#define rc_bitblt_wm_orn_bin_SCORE                           1.29e+09

#define rc_bitblt_wm_nandn_bin_IMPL                          RC_IMPL_GEN
#define rc_bitblt_wm_nandn_bin_UNROLL                        4
#define rc_bitblt_wm_nandn_bin_SCORE                         1.28e+09

#define rc_bitblt_wm_norn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wm_norn_bin_UNROLL                         4
#define rc_bitblt_wm_norn_bin_SCORE                          1.28e+09

#define rc_bitblt_wa_copy_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_copy_bin_UNROLL                         4
#define rc_bitblt_wa_copy_bin_SCORE                          3.42e+09

#define rc_bitblt_wa_not_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_not_bin_UNROLL                          4
#define rc_bitblt_wa_not_bin_SCORE                           2.73e+09

#define rc_bitblt_wa_and_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_and_bin_UNROLL                          4
#define rc_bitblt_wa_and_bin_SCORE                           2.26e+09

#define rc_bitblt_wa_or_bin_IMPL                             RC_IMPL_GEN
#define rc_bitblt_wa_or_bin_UNROLL                           4
#define rc_bitblt_wa_or_bin_SCORE                            2.26e+09

#define rc_bitblt_wa_xor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_xor_bin_UNROLL                          4
#define rc_bitblt_wa_xor_bin_SCORE                           2.25e+09

#define rc_bitblt_wa_nand_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_nand_bin_UNROLL                         4
#define rc_bitblt_wa_nand_bin_SCORE                          1.93e+09

#define rc_bitblt_wa_nor_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_nor_bin_UNROLL                          4
#define rc_bitblt_wa_nor_bin_SCORE                           1.93e+09

#define rc_bitblt_wa_xnor_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_xnor_bin_UNROLL                         4
#define rc_bitblt_wa_xnor_bin_SCORE                          1.94e+09

#define rc_bitblt_wa_andn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_andn_bin_UNROLL                         4
#define rc_bitblt_wa_andn_bin_SCORE                          2.00e+09

#define rc_bitblt_wa_orn_bin_IMPL                            RC_IMPL_GEN
#define rc_bitblt_wa_orn_bin_UNROLL                          4
#define rc_bitblt_wa_orn_bin_SCORE                           1.99e+09

#define rc_bitblt_wa_nandn_bin_IMPL                          RC_IMPL_GEN
#define rc_bitblt_wa_nandn_bin_UNROLL                        4
#define rc_bitblt_wa_nandn_bin_SCORE                         1.97e+09

#define rc_bitblt_wa_norn_bin_IMPL                           RC_IMPL_GEN
#define rc_bitblt_wa_norn_bin_UNROLL                         4
#define rc_bitblt_wa_norn_bin_SCORE                          1.97e+09

#define rc_bitblt_vm_copy_bin_IMPL                           RC_IMPL_SIMD
#define rc_bitblt_vm_copy_bin_UNROLL                         1
#define rc_bitblt_vm_copy_bin_SCORE                          3.56e+09

#define rc_bitblt_vm_not_bin_IMPL                            RC_IMPL_SIMD
#define rc_bitblt_vm_not_bin_UNROLL                          1
#define rc_bitblt_vm_not_bin_SCORE                           3.15e+09

#define rc_bitblt_vm_and_bin_IMPL                            RC_IMPL_SIMD
#define rc_bitblt_vm_and_bin_UNROLL                          1
#define rc_bitblt_vm_and_bin_SCORE                           2.76e+09

#define rc_bitblt_vm_or_bin_IMPL                             RC_IMPL_SIMD
#define rc_bitblt_vm_or_bin_UNROLL                           1
#define rc_bitblt_vm_or_bin_SCORE                            2.76e+09

#define rc_bitblt_vm_xor_bin_IMPL                            RC_IMPL_SIMD
#define rc_bitblt_vm_xor_bin_UNROLL                          1
#define rc_bitblt_vm_xor_bin_SCORE                           2.76e+09

#define rc_bitblt_vm_nand_bin_IMPL                           RC_IMPL_SIMD
#define rc_bitblt_vm_nand_bin_UNROLL                         1
#define rc_bitblt_vm_nand_bin_SCORE                          2.76e+09

#define rc_bitblt_vm_nor_bin_IMPL                            RC_IMPL_SIMD
#define rc_bitblt_vm_nor_bin_UNROLL                          1
#define rc_bitblt_vm_nor_bin_SCORE                           2.76e+09

#define rc_bitblt_vm_xnor_bin_IMPL                           RC_IMPL_SIMD
#define rc_bitblt_vm_xnor_bin_UNROLL                         1
#define rc_bitblt_vm_xnor_bin_SCORE                          2.75e+09

#define rc_bitblt_vm_andn_bin_IMPL                           RC_IMPL_SIMD
#define rc_bitblt_vm_andn_bin_UNROLL                         1
#define rc_bitblt_vm_andn_bin_SCORE                          2.76e+09

#define rc_bitblt_vm_orn_bin_IMPL                            RC_IMPL_SIMD
#define rc_bitblt_vm_orn_bin_UNROLL                          1
#define rc_bitblt_vm_orn_bin_SCORE                           2.75e+09

#define rc_bitblt_vm_nandn_bin_IMPL                          RC_IMPL_SIMD
#define rc_bitblt_vm_nandn_bin_UNROLL                        1
#define rc_bitblt_vm_nandn_bin_SCORE                         2.76e+09

#define rc_bitblt_vm_norn_bin_IMPL                           RC_IMPL_SIMD
#define rc_bitblt_vm_norn_bin_UNROLL                         1
#define rc_bitblt_vm_norn_bin_SCORE                          2.76e+09

#define rc_bitblt_va_copy_bin_IMPL                           RC_IMPL_SIMD
#define rc_bitblt_va_copy_bin_UNROLL                         2
#define rc_bitblt_va_copy_bin_SCORE                          5.01e+09

#define rc_bitblt_va_not_bin_IMPL                            RC_IMPL_SIMD
#define rc_bitblt_va_not_bin_UNROLL                          2
#define rc_bitblt_va_not_bin_SCORE                           4.49e+09

#define rc_bitblt_va_and_bin_IMPL                            RC_IMPL_SIMD
#define rc_bitblt_va_and_bin_UNROLL                          1
#define rc_bitblt_va_and_bin_SCORE                           3.55e+09

#define rc_bitblt_va_or_bin_IMPL                             RC_IMPL_SIMD
#define rc_bitblt_va_or_bin_UNROLL                           1
#define rc_bitblt_va_or_bin_SCORE                            3.54e+09

#define rc_bitblt_va_xor_bin_IMPL                            RC_IMPL_SIMD
#define rc_bitblt_va_xor_bin_UNROLL                          1
#define rc_bitblt_va_xor_bin_SCORE                           3.54e+09

#define rc_bitblt_va_nand_bin_IMPL                           RC_IMPL_SIMD
#define rc_bitblt_va_nand_bin_UNROLL                         1
#define rc_bitblt_va_nand_bin_SCORE                          3.54e+09

#define rc_bitblt_va_nor_bin_IMPL                            RC_IMPL_SIMD
#define rc_bitblt_va_nor_bin_UNROLL                          1
#define rc_bitblt_va_nor_bin_SCORE                           3.55e+09

#define rc_bitblt_va_xnor_bin_IMPL                           RC_IMPL_SIMD
#define rc_bitblt_va_xnor_bin_UNROLL                         1
#define rc_bitblt_va_xnor_bin_SCORE                          3.47e+09

#define rc_bitblt_va_andn_bin_IMPL                           RC_IMPL_SIMD
#define rc_bitblt_va_andn_bin_UNROLL                         1
#define rc_bitblt_va_andn_bin_SCORE                          3.47e+09

#define rc_bitblt_va_orn_bin_IMPL                            RC_IMPL_SIMD
#define rc_bitblt_va_orn_bin_UNROLL                          1
#define rc_bitblt_va_orn_bin_SCORE                           3.48e+09

#define rc_bitblt_va_nandn_bin_IMPL                          RC_IMPL_SIMD
#define rc_bitblt_va_nandn_bin_UNROLL                        1
#define rc_bitblt_va_nandn_bin_SCORE                         3.46e+09

#define rc_bitblt_va_norn_bin_IMPL                           RC_IMPL_SIMD
#define rc_bitblt_va_norn_bin_UNROLL                         1
#define rc_bitblt_va_norn_bin_SCORE                          3.45e+09

#define rc_pixop_set_u8_IMPL                                 RC_IMPL_SIMD
#define rc_pixop_set_u8_UNROLL                               1
#define rc_pixop_set_u8_SCORE                                1.33e+09

#define rc_pixop_not_u8_IMPL                                 RC_IMPL_SIMD
#define rc_pixop_not_u8_UNROLL                               4
#define rc_pixop_not_u8_SCORE                                5.92e+08

#define rc_pixop_flip_u8_IMPL                                RC_IMPL_SIMD
#define rc_pixop_flip_u8_UNROLL                              4
#define rc_pixop_flip_u8_SCORE                               6.02e+08

#define rc_pixop_lut_u8_IMPL                                 RC_IMPL_GEN
#define rc_pixop_lut_u8_UNROLL                               4
#define rc_pixop_lut_u8_SCORE                                1.00e+08

#define rc_pixop_abs_u8_IMPL                                 RC_IMPL_SIMD
#define rc_pixop_abs_u8_UNROLL                               4
#define rc_pixop_abs_u8_SCORE                                5.37e+08

#define rc_pixop_addc_u8_IMPL                                RC_IMPL_SIMD
#define rc_pixop_addc_u8_UNROLL                              4
#define rc_pixop_addc_u8_SCORE                               5.91e+08

#define rc_pixop_lerpc_u8_IMPL                               RC_IMPL_SIMD
#define rc_pixop_lerpc_u8_UNROLL                             4
#define rc_pixop_lerpc_u8_SCORE                              5.93e+08

#define rc_pixop_lerpnc_u8_IMPL                              RC_IMPL_SIMD
#define rc_pixop_lerpnc_u8_UNROLL                            4
#define rc_pixop_lerpnc_u8_SCORE                             5.92e+08

#define rc_pixop_add_u8_IMPL                                 RC_IMPL_SIMD
#define rc_pixop_add_u8_UNROLL                               4
#define rc_pixop_add_u8_SCORE                                1.93e+08

#define rc_pixop_avg_u8_IMPL                                 RC_IMPL_SIMD
#define rc_pixop_avg_u8_UNROLL                               4
#define rc_pixop_avg_u8_SCORE                                1.96e+08

#define rc_pixop_sub_u8_IMPL                                 RC_IMPL_SIMD
#define rc_pixop_sub_u8_UNROLL                               4
#define rc_pixop_sub_u8_SCORE                                1.93e+08

#define rc_pixop_subh_u8_IMPL                                RC_IMPL_SIMD
#define rc_pixop_subh_u8_UNROLL                              4
#define rc_pixop_subh_u8_SCORE                               1.95e+08

#define rc_pixop_suba_u8_IMPL                                RC_IMPL_SIMD
#define rc_pixop_suba_u8_UNROLL                              4
#define rc_pixop_suba_u8_SCORE                               1.96e+08

#define rc_pixop_lerp_u8_IMPL                                RC_IMPL_SIMD
#define rc_pixop_lerp_u8_UNROLL                              4
#define rc_pixop_lerp_u8_SCORE                               1.93e+08

#define rc_pixop_lerpn_u8_IMPL                               RC_IMPL_SIMD
#define rc_pixop_lerpn_u8_UNROLL                             1
#define rc_pixop_lerpn_u8_SCORE                              1.40e+08

#define rc_pixop_lerpi_u8_IMPL                               RC_IMPL_SIMD
#define rc_pixop_lerpi_u8_UNROLL                             2
#define rc_pixop_lerpi_u8_SCORE                              1.86e+08

#define rc_pixop_norm_u8_IMPL                                RC_IMPL_SIMD
#define rc_pixop_norm_u8_UNROLL                              2
#define rc_pixop_norm_u8_SCORE                               1.81e+08

#define rc_type_u8_to_bin_IMPL                               RC_IMPL_SIMD
#define rc_type_u8_to_bin_UNROLL                             4
#define rc_type_u8_to_bin_SCORE                              4.88e+08

#define rc_type_bin_to_u8_IMPL                               RC_IMPL_SIMD
#define rc_type_bin_to_u8_UNROLL                             2
#define rc_type_bin_to_u8_SCORE                              7.38e+08

#define rc_thresh_gt_u8_IMPL                                 RC_IMPL_SIMD
#define rc_thresh_gt_u8_UNROLL                               1
#define rc_thresh_gt_u8_SCORE                                4.65e+08

#define rc_thresh_lt_u8_IMPL                                 RC_IMPL_SIMD
#define rc_thresh_lt_u8_UNROLL                               1
#define rc_thresh_lt_u8_SCORE                                4.66e+08

#define rc_thresh_gtlt_u8_IMPL                               RC_IMPL_SIMD
#define rc_thresh_gtlt_u8_UNROLL                             1
#define rc_thresh_gtlt_u8_SCORE                              4.03e+08

#define rc_thresh_ltgt_u8_IMPL                               RC_IMPL_SIMD
#define rc_thresh_ltgt_u8_UNROLL                             1
#define rc_thresh_ltgt_u8_SCORE                              4.02e+08

#define rc_thresh_gt_pixel_u8_IMPL                           RC_IMPL_SIMD
#define rc_thresh_gt_pixel_u8_UNROLL                         4
#define rc_thresh_gt_pixel_u8_SCORE                          2.00e+08

#define rc_thresh_lt_pixel_u8_IMPL                           RC_IMPL_SIMD
#define rc_thresh_lt_pixel_u8_UNROLL                         4
#define rc_thresh_lt_pixel_u8_SCORE                          1.99e+08

#define rc_thresh_gtlt_pixel_u8_IMPL                         RC_IMPL_SIMD
#define rc_thresh_gtlt_pixel_u8_UNROLL                       2
#define rc_thresh_gtlt_pixel_u8_SCORE                        1.25e+08

#define rc_thresh_ltgt_pixel_u8_IMPL                         RC_IMPL_SIMD
#define rc_thresh_ltgt_pixel_u8_UNROLL                       2
#define rc_thresh_ltgt_pixel_u8_SCORE                        1.25e+08

#define rc_stat_sum_bin_IMPL                                 RC_IMPL_SIMD
#define rc_stat_sum_bin_UNROLL                               1
#define rc_stat_sum_bin_SCORE                                5.81e+09

#define rc_stat_sum_u8_IMPL                                  RC_IMPL_SIMD
#define rc_stat_sum_u8_UNROLL                                1
#define rc_stat_sum_u8_SCORE                                 6.87e+08

#define rc_stat_sum2_u8_IMPL                                 RC_IMPL_SIMD
#define rc_stat_sum2_u8_UNROLL                               1
#define rc_stat_sum2_u8_SCORE                                3.99e+08

#define rc_stat_xsum_u8_IMPL                                 RC_IMPL_SIMD
#define rc_stat_xsum_u8_UNROLL                               1
#define rc_stat_xsum_u8_SCORE                                1.04e+08

#define rc_stat_min_bin_IMPL                                 RC_IMPL_SIMD
#define rc_stat_min_bin_UNROLL                               2
#define rc_stat_min_bin_SCORE                                6.24e+09

#define rc_stat_max_bin_IMPL                                 RC_IMPL_SIMD
#define rc_stat_max_bin_UNROLL                               2
#define rc_stat_max_bin_SCORE                                6.26e+09

#define rc_stat_min_u8_IMPL                                  RC_IMPL_SIMD
#define rc_stat_min_u8_UNROLL                                4
#define rc_stat_min_u8_SCORE                                 7.17e+08

#define rc_stat_max_u8_IMPL                                  RC_IMPL_SIMD
#define rc_stat_max_u8_UNROLL                                4
#define rc_stat_max_u8_SCORE                                 7.21e+08

#define rc_reduce_1x2_u8_IMPL                                RC_IMPL_SIMD
#define rc_reduce_1x2_u8_UNROLL                              2
#define rc_reduce_1x2_u8_SCORE                               3.86e+08

#define rc_reduce_2x1_u8_IMPL                                RC_IMPL_SIMD
#define rc_reduce_2x1_u8_UNROLL                              1
#define rc_reduce_2x1_u8_SCORE                               3.82e+08

#define rc_reduce_2x2_u8_IMPL                                RC_IMPL_SIMD
#define rc_reduce_2x2_u8_UNROLL                              2
#define rc_reduce_2x2_u8_SCORE                               4.72e+08

#define rc_reduce_1x2_rk1_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_1x2_rk1_bin_UNROLL                         1
#define rc_reduce_1x2_rk1_bin_SCORE                          9.20e+08

#define rc_reduce_1x2_rk2_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_1x2_rk2_bin_UNROLL                         1
#define rc_reduce_1x2_rk2_bin_SCORE                          9.30e+08

#define rc_reduce_2x1_rk1_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x1_rk1_bin_UNROLL                         2
#define rc_reduce_2x1_rk1_bin_SCORE                          4.17e+09

#define rc_reduce_2x1_rk2_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x1_rk2_bin_UNROLL                         2
#define rc_reduce_2x1_rk2_bin_SCORE                          4.17e+09

#define rc_reduce_2x2_rk1_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk1_bin_UNROLL                         2
#define rc_reduce_2x2_rk1_bin_SCORE                          1.41e+09

#define rc_reduce_2x2_rk2_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk2_bin_UNROLL                         1
#define rc_reduce_2x2_rk2_bin_SCORE                          1.16e+09

#define rc_reduce_2x2_rk3_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk3_bin_UNROLL                         1
#define rc_reduce_2x2_rk3_bin_SCORE                          1.16e+09

#define rc_reduce_2x2_rk4_bin_IMPL                           RC_IMPL_GEN
#define rc_reduce_2x2_rk4_bin_UNROLL                         4
#define rc_reduce_2x2_rk4_bin_SCORE                          1.43e+09

#define rc_expand_1x2_bin_IMPL                               RC_IMPL_GEN
#define rc_expand_1x2_bin_UNROLL                             4
#define rc_expand_1x2_bin_SCORE                              5.74e+08

#define rc_expand_2x1_bin_IMPL                               RC_IMPL_GEN
#define rc_expand_2x1_bin_UNROLL                             4
#define rc_expand_2x1_bin_SCORE                              2.46e+09

#define rc_expand_2x2_bin_IMPL                               RC_IMPL_GEN
#define rc_expand_2x2_bin_UNROLL                             4
#define rc_expand_2x2_bin_SCORE                              5.09e+08

#define rc_rotate_cw_u8_IMPL                                 RC_IMPL_GEN
#define rc_rotate_cw_u8_UNROLL                               1
#define rc_rotate_cw_u8_SCORE                                3.59e+07

#define rc_rotate_ccw_u8_IMPL                                RC_IMPL_GEN
#define rc_rotate_ccw_u8_UNROLL                              1
#define rc_rotate_ccw_u8_SCORE                               3.15e+07

#define rc_filter_diff_1x2_horz_u8_IMPL                      RC_IMPL_SIMD
#define rc_filter_diff_1x2_horz_u8_UNROLL                    1
#define rc_filter_diff_1x2_horz_u8_SCORE                     2.75e+08

#define rc_filter_diff_1x2_horz_abs_u8_IMPL                  RC_IMPL_SIMD
#define rc_filter_diff_1x2_horz_abs_u8_UNROLL                1
#define rc_filter_diff_1x2_horz_abs_u8_SCORE                 2.78e+08

#define rc_filter_diff_2x1_vert_u8_IMPL                      RC_IMPL_SIMD
#define rc_filter_diff_2x1_vert_u8_UNROLL                    1
#define rc_filter_diff_2x1_vert_u8_SCORE                     2.35e+08

#define rc_filter_diff_2x1_vert_abs_u8_IMPL                  RC_IMPL_SIMD
#define rc_filter_diff_2x1_vert_abs_u8_UNROLL                1
#define rc_filter_diff_2x1_vert_abs_u8_SCORE                 2.36e+08

#define rc_filter_diff_2x2_magn_u8_IMPL                      RC_IMPL_SIMD
#define rc_filter_diff_2x2_magn_u8_UNROLL                    2
#define rc_filter_diff_2x2_magn_u8_SCORE                     2.00e+08

#define rc_filter_sobel_3x3_horz_u8_IMPL                     RC_IMPL_SIMD
#define rc_filter_sobel_3x3_horz_u8_UNROLL                   1
#define rc_filter_sobel_3x3_horz_u8_SCORE                    1.66e+08

#define rc_filter_sobel_3x3_horz_abs_u8_IMPL                 RC_IMPL_SIMD
#define rc_filter_sobel_3x3_horz_abs_u8_UNROLL               1
#define rc_filter_sobel_3x3_horz_abs_u8_SCORE                1.85e+08

#define rc_filter_sobel_3x3_vert_u8_IMPL                     RC_IMPL_SIMD
#define rc_filter_sobel_3x3_vert_u8_UNROLL                   1
#define rc_filter_sobel_3x3_vert_u8_SCORE                    2.01e+08

#define rc_filter_sobel_3x3_vert_abs_u8_IMPL                 RC_IMPL_SIMD
#define rc_filter_sobel_3x3_vert_abs_u8_UNROLL               1
#define rc_filter_sobel_3x3_vert_abs_u8_SCORE                1.60e+08

#define rc_filter_sobel_3x3_magn_u8_IMPL                     RC_IMPL_SIMD
#define rc_filter_sobel_3x3_magn_u8_UNROLL                   1
#define rc_filter_sobel_3x3_magn_u8_SCORE                    1.47e+08

#define rc_filter_gauss_3x3_u8_IMPL                          RC_IMPL_SIMD
#define rc_filter_gauss_3x3_u8_UNROLL                        1
#define rc_filter_gauss_3x3_u8_SCORE                         1.80e+08

#define rc_filter_laplace_3x3_u8_IMPL                        RC_IMPL_SIMD
#define rc_filter_laplace_3x3_u8_UNROLL                      1
#define rc_filter_laplace_3x3_u8_SCORE                       1.72e+08

#define rc_filter_laplace_3x3_abs_u8_IMPL                    RC_IMPL_SIMD
#define rc_filter_laplace_3x3_abs_u8_UNROLL                  1
#define rc_filter_laplace_3x3_abs_u8_SCORE                   1.73e+08

#define rc_filter_highpass_3x3_u8_IMPL                       RC_IMPL_SIMD
#define rc_filter_highpass_3x3_u8_UNROLL                     1
#define rc_filter_highpass_3x3_u8_SCORE                      1.08e+08

#define rc_filter_highpass_3x3_abs_u8_IMPL                   RC_IMPL_SIMD
#define rc_filter_highpass_3x3_abs_u8_UNROLL                 1
#define rc_filter_highpass_3x3_abs_u8_SCORE                  1.07e+08

#define rc_morph_erode_line_1x2_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_1x2_bin_UNROLL                   4
#define rc_morph_erode_line_1x2_bin_SCORE                    1.73e+09

#define rc_morph_dilate_line_1x2_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_1x2_bin_UNROLL                  4
#define rc_morph_dilate_line_1x2_bin_SCORE                   1.77e+09

#define rc_morph_erode_line_1x3_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_1x3_bin_UNROLL                   4
#define rc_morph_erode_line_1x3_bin_SCORE                    1.13e+09

#define rc_morph_dilate_line_1x3_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_1x3_bin_UNROLL                  4
#define rc_morph_dilate_line_1x3_bin_SCORE                   1.15e+09

#define rc_morph_erode_line_1x3_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x3_p_bin_UNROLL                 4
#define rc_morph_erode_line_1x3_p_bin_SCORE                  1.29e+09

#define rc_morph_dilate_line_1x3_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x3_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x3_p_bin_SCORE                 1.28e+09

#define rc_morph_erode_line_1x5_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x5_p_bin_UNROLL                 4
#define rc_morph_erode_line_1x5_p_bin_SCORE                  1.29e+09

#define rc_morph_dilate_line_1x5_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x5_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x5_p_bin_SCORE                 1.28e+09

#define rc_morph_erode_line_1x7_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x7_p_bin_UNROLL                 4
#define rc_morph_erode_line_1x7_p_bin_SCORE                  1.29e+09

#define rc_morph_dilate_line_1x7_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x7_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x7_p_bin_SCORE                 1.28e+09

#define rc_morph_erode_line_1x9_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_1x9_p_bin_UNROLL                 4
#define rc_morph_erode_line_1x9_p_bin_SCORE                  1.29e+09

#define rc_morph_dilate_line_1x9_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_1x9_p_bin_UNROLL                4
#define rc_morph_dilate_line_1x9_p_bin_SCORE                 1.28e+09

#define rc_morph_erode_line_1x13_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x13_p_bin_UNROLL                4
#define rc_morph_erode_line_1x13_p_bin_SCORE                 1.29e+09

#define rc_morph_dilate_line_1x13_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x13_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x13_p_bin_SCORE                1.28e+09

#define rc_morph_erode_line_1x15_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x15_p_bin_UNROLL                4
#define rc_morph_erode_line_1x15_p_bin_SCORE                 1.29e+09

#define rc_morph_dilate_line_1x15_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x15_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x15_p_bin_SCORE                1.28e+09

#define rc_morph_erode_line_1x17_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x17_p_bin_UNROLL                4
#define rc_morph_erode_line_1x17_p_bin_SCORE                 1.29e+09

#define rc_morph_dilate_line_1x17_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x17_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x17_p_bin_SCORE                1.29e+09

#define rc_morph_erode_line_1x25_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x25_p_bin_UNROLL                4
#define rc_morph_erode_line_1x25_p_bin_SCORE                 1.29e+09

#define rc_morph_dilate_line_1x25_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x25_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x25_p_bin_SCORE                1.28e+09

#define rc_morph_erode_line_1x29_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x29_p_bin_UNROLL                4
#define rc_morph_erode_line_1x29_p_bin_SCORE                 1.29e+09

#define rc_morph_dilate_line_1x29_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x29_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x29_p_bin_SCORE                1.29e+09

#define rc_morph_erode_line_1x31_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_1x31_p_bin_UNROLL                4
#define rc_morph_erode_line_1x31_p_bin_SCORE                 1.29e+09

#define rc_morph_dilate_line_1x31_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_1x31_p_bin_UNROLL               4
#define rc_morph_dilate_line_1x31_p_bin_SCORE                1.28e+09

#define rc_morph_erode_line_2x1_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_2x1_bin_UNROLL                   4
#define rc_morph_erode_line_2x1_bin_SCORE                    2.32e+09

#define rc_morph_dilate_line_2x1_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_2x1_bin_UNROLL                  4
#define rc_morph_dilate_line_2x1_bin_SCORE                   2.32e+09

#define rc_morph_erode_line_3x1_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_line_3x1_bin_UNROLL                   4
#define rc_morph_erode_line_3x1_bin_SCORE                    1.70e+09

#define rc_morph_dilate_line_3x1_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_line_3x1_bin_UNROLL                  4
#define rc_morph_dilate_line_3x1_bin_SCORE                   1.70e+09

#define rc_morph_erode_line_3x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_3x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_3x1_p_bin_SCORE                  2.24e+09

#define rc_morph_dilate_line_3x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_3x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_3x1_p_bin_SCORE                 2.19e+09

#define rc_morph_erode_line_5x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_5x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_5x1_p_bin_SCORE                  2.31e+09

#define rc_morph_dilate_line_5x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_5x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_5x1_p_bin_SCORE                 2.31e+09

#define rc_morph_erode_line_7x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_7x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_7x1_p_bin_SCORE                  2.31e+09

#define rc_morph_dilate_line_7x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_7x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_7x1_p_bin_SCORE                 2.31e+09

#define rc_morph_erode_line_9x1_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_line_9x1_p_bin_UNROLL                 4
#define rc_morph_erode_line_9x1_p_bin_SCORE                  2.30e+09

#define rc_morph_dilate_line_9x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_line_9x1_p_bin_UNROLL                4
#define rc_morph_dilate_line_9x1_p_bin_SCORE                 2.30e+09

#define rc_morph_erode_line_13x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_13x1_p_bin_UNROLL                4
#define rc_morph_erode_line_13x1_p_bin_SCORE                 2.29e+09

#define rc_morph_dilate_line_13x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_13x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_13x1_p_bin_SCORE                2.30e+09

#define rc_morph_erode_line_15x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_15x1_p_bin_UNROLL                4
#define rc_morph_erode_line_15x1_p_bin_SCORE                 2.30e+09

#define rc_morph_dilate_line_15x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_15x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_15x1_p_bin_SCORE                2.29e+09

#define rc_morph_erode_line_17x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_17x1_p_bin_UNROLL                4
#define rc_morph_erode_line_17x1_p_bin_SCORE                 2.29e+09

#define rc_morph_dilate_line_17x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_17x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_17x1_p_bin_SCORE                2.28e+09

#define rc_morph_erode_line_25x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_25x1_p_bin_UNROLL                4
#define rc_morph_erode_line_25x1_p_bin_SCORE                 2.26e+09

#define rc_morph_dilate_line_25x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_25x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_25x1_p_bin_SCORE                2.27e+09

#define rc_morph_erode_line_29x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_29x1_p_bin_UNROLL                4
#define rc_morph_erode_line_29x1_p_bin_SCORE                 2.26e+09

#define rc_morph_dilate_line_29x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_29x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_29x1_p_bin_SCORE                2.27e+09

#define rc_morph_erode_line_31x1_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_line_31x1_p_bin_UNROLL                4
#define rc_morph_erode_line_31x1_p_bin_SCORE                 2.27e+09

#define rc_morph_dilate_line_31x1_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_line_31x1_p_bin_UNROLL               4
#define rc_morph_dilate_line_31x1_p_bin_SCORE                2.26e+09

#define rc_morph_erode_square_2x2_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_square_2x2_bin_UNROLL                 1
#define rc_morph_erode_square_2x2_bin_SCORE                  8.76e+08

#define rc_morph_dilate_square_2x2_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_square_2x2_bin_UNROLL                4
#define rc_morph_dilate_square_2x2_bin_SCORE                 9.76e+08

#define rc_morph_erode_square_3x3_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_square_3x3_bin_UNROLL                 4
#define rc_morph_erode_square_3x3_bin_SCORE                  3.92e+08

#define rc_morph_dilate_square_3x3_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_square_3x3_bin_UNROLL                4
#define rc_morph_dilate_square_3x3_bin_SCORE                 3.98e+08

#define rc_morph_erode_square_3x3_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_square_3x3_p_bin_UNROLL               4
#define rc_morph_erode_square_3x3_p_bin_SCORE                6.15e+08

#define rc_morph_dilate_square_3x3_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_square_3x3_p_bin_UNROLL              4
#define rc_morph_dilate_square_3x3_p_bin_SCORE               6.04e+08

#define rc_morph_erode_diamond_3x3_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_erode_diamond_3x3_bin_UNROLL                4
#define rc_morph_erode_diamond_3x3_bin_SCORE                 8.48e+08

#define rc_morph_dilate_diamond_3x3_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_dilate_diamond_3x3_bin_UNROLL               4
#define rc_morph_dilate_diamond_3x3_bin_SCORE                8.46e+08

#define rc_morph_erode_diamond_3x3_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_3x3_p_bin_UNROLL              4
#define rc_morph_erode_diamond_3x3_p_bin_SCORE               9.04e+08

#define rc_morph_dilate_diamond_3x3_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_3x3_p_bin_UNROLL             4
#define rc_morph_dilate_diamond_3x3_p_bin_SCORE              8.86e+08

#define rc_morph_erode_diamond_5x5_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_5x5_p_bin_UNROLL              4
#define rc_morph_erode_diamond_5x5_p_bin_SCORE               9.08e+08

#define rc_morph_dilate_diamond_5x5_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_5x5_p_bin_UNROLL             4
#define rc_morph_dilate_diamond_5x5_p_bin_SCORE              8.85e+08

#define rc_morph_erode_diamond_7x7_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_7x7_p_bin_UNROLL              4
#define rc_morph_erode_diamond_7x7_p_bin_SCORE               9.05e+08

#define rc_morph_dilate_diamond_7x7_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_7x7_p_bin_UNROLL             4
#define rc_morph_dilate_diamond_7x7_p_bin_SCORE              8.92e+08

#define rc_morph_erode_diamond_9x9_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_diamond_9x9_p_bin_UNROLL              4
#define rc_morph_erode_diamond_9x9_p_bin_SCORE               9.05e+08

#define rc_morph_dilate_diamond_9x9_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_diamond_9x9_p_bin_UNROLL             4
#define rc_morph_dilate_diamond_9x9_p_bin_SCORE              8.81e+08

#define rc_morph_erode_diamond_13x13_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_13x13_p_bin_UNROLL            4
#define rc_morph_erode_diamond_13x13_p_bin_SCORE             9.13e+08

#define rc_morph_dilate_diamond_13x13_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_13x13_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_13x13_p_bin_SCORE            8.93e+08

#define rc_morph_erode_diamond_15x15_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_15x15_p_bin_UNROLL            4
#define rc_morph_erode_diamond_15x15_p_bin_SCORE             9.03e+08

#define rc_morph_dilate_diamond_15x15_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_15x15_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_15x15_p_bin_SCORE            8.93e+08

#define rc_morph_erode_diamond_17x17_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_17x17_p_bin_UNROLL            4
#define rc_morph_erode_diamond_17x17_p_bin_SCORE             9.04e+08

#define rc_morph_dilate_diamond_17x17_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_17x17_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_17x17_p_bin_SCORE            8.85e+08

#define rc_morph_erode_diamond_25x25_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_25x25_p_bin_UNROLL            4
#define rc_morph_erode_diamond_25x25_p_bin_SCORE             9.06e+08

#define rc_morph_dilate_diamond_25x25_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_25x25_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_25x25_p_bin_SCORE            8.85e+08

#define rc_morph_erode_diamond_29x29_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_29x29_p_bin_UNROLL            4
#define rc_morph_erode_diamond_29x29_p_bin_SCORE             9.08e+08

#define rc_morph_dilate_diamond_29x29_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_29x29_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_29x29_p_bin_SCORE            8.83e+08

#define rc_morph_erode_diamond_31x31_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_diamond_31x31_p_bin_UNROLL            4
#define rc_morph_erode_diamond_31x31_p_bin_SCORE             8.96e+08

#define rc_morph_dilate_diamond_31x31_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_diamond_31x31_p_bin_UNROLL           4
#define rc_morph_dilate_diamond_31x31_p_bin_SCORE            8.86e+08

#define rc_morph_erode_octagon_5x5_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_octagon_5x5_p_bin_UNROLL              4
#define rc_morph_erode_octagon_5x5_p_bin_SCORE               3.15e+08

#define rc_morph_dilate_octagon_5x5_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_octagon_5x5_p_bin_UNROLL             4
#define rc_morph_dilate_octagon_5x5_p_bin_SCORE              3.21e+08

#define rc_morph_erode_octagon_7x7_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_octagon_7x7_p_bin_UNROLL              4
#define rc_morph_erode_octagon_7x7_p_bin_SCORE               3.14e+08

#define rc_morph_dilate_octagon_7x7_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_octagon_7x7_p_bin_UNROLL             4
#define rc_morph_dilate_octagon_7x7_p_bin_SCORE              3.21e+08

#define rc_morph_erode_octagon_9x9_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_erode_octagon_9x9_p_bin_UNROLL              4
#define rc_morph_erode_octagon_9x9_p_bin_SCORE               3.15e+08

#define rc_morph_dilate_octagon_9x9_p_bin_IMPL               RC_IMPL_GEN
#define rc_morph_dilate_octagon_9x9_p_bin_UNROLL             4
#define rc_morph_dilate_octagon_9x9_p_bin_SCORE              3.20e+08

#define rc_morph_erode_octagon_13x13_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_13x13_p_bin_UNROLL            4
#define rc_morph_erode_octagon_13x13_p_bin_SCORE             3.14e+08

#define rc_morph_dilate_octagon_13x13_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_13x13_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_13x13_p_bin_SCORE            3.21e+08

#define rc_morph_erode_octagon_15x15_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_15x15_p_bin_UNROLL            4
#define rc_morph_erode_octagon_15x15_p_bin_SCORE             3.13e+08

#define rc_morph_dilate_octagon_15x15_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_15x15_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_15x15_p_bin_SCORE            3.20e+08

#define rc_morph_erode_octagon_17x17_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_17x17_p_bin_UNROLL            4
#define rc_morph_erode_octagon_17x17_p_bin_SCORE             3.19e+08

#define rc_morph_dilate_octagon_17x17_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_17x17_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_17x17_p_bin_SCORE            3.28e+08

#define rc_morph_erode_octagon_25x25_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_25x25_p_bin_UNROLL            4
#define rc_morph_erode_octagon_25x25_p_bin_SCORE             3.14e+08

#define rc_morph_dilate_octagon_25x25_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_25x25_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_25x25_p_bin_SCORE            3.20e+08

#define rc_morph_erode_octagon_29x29_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_29x29_p_bin_UNROLL            4
#define rc_morph_erode_octagon_29x29_p_bin_SCORE             3.13e+08

#define rc_morph_dilate_octagon_29x29_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_29x29_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_29x29_p_bin_SCORE            3.19e+08

#define rc_morph_erode_octagon_31x31_p_bin_IMPL              RC_IMPL_GEN
#define rc_morph_erode_octagon_31x31_p_bin_UNROLL            4
#define rc_morph_erode_octagon_31x31_p_bin_SCORE             3.15e+08

#define rc_morph_dilate_octagon_31x31_p_bin_IMPL             RC_IMPL_GEN
#define rc_morph_dilate_octagon_31x31_p_bin_UNROLL           4
#define rc_morph_dilate_octagon_31x31_p_bin_SCORE            3.20e+08

#define rc_morph_erode_disc_7x7_bin_IMPL                     RC_IMPL_GEN
#define rc_morph_erode_disc_7x7_bin_UNROLL                   1
#define rc_morph_erode_disc_7x7_bin_SCORE                    1.25e+08

#define rc_morph_dilate_disc_7x7_bin_IMPL                    RC_IMPL_GEN
#define rc_morph_dilate_disc_7x7_bin_UNROLL                  1
#define rc_morph_dilate_disc_7x7_bin_SCORE                   1.25e+08

#define rc_morph_erode_disc_7x7_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_disc_7x7_p_bin_UNROLL                 4
#define rc_morph_erode_disc_7x7_p_bin_SCORE                  3.67e+08

#define rc_morph_dilate_disc_7x7_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_disc_7x7_p_bin_UNROLL                4
#define rc_morph_dilate_disc_7x7_p_bin_SCORE                 3.74e+08

#define rc_morph_erode_disc_9x9_p_bin_IMPL                   RC_IMPL_GEN
#define rc_morph_erode_disc_9x9_p_bin_UNROLL                 4
#define rc_morph_erode_disc_9x9_p_bin_SCORE                  3.77e+08

#define rc_morph_dilate_disc_9x9_p_bin_IMPL                  RC_IMPL_GEN
#define rc_morph_dilate_disc_9x9_p_bin_UNROLL                4
#define rc_morph_dilate_disc_9x9_p_bin_SCORE                 3.83e+08

#define rc_morph_erode_disc_11x11_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_11x11_p_bin_UNROLL               4
#define rc_morph_erode_disc_11x11_p_bin_SCORE                1.88e+08

#define rc_morph_dilate_disc_11x11_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_11x11_p_bin_UNROLL              4
#define rc_morph_dilate_disc_11x11_p_bin_SCORE               1.85e+08

#define rc_morph_erode_disc_13x13_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_13x13_p_bin_UNROLL               1
#define rc_morph_erode_disc_13x13_p_bin_SCORE                1.38e+08

#define rc_morph_dilate_disc_13x13_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_13x13_p_bin_UNROLL              4
#define rc_morph_dilate_disc_13x13_p_bin_SCORE               1.42e+08

#define rc_morph_erode_disc_15x15_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_15x15_p_bin_UNROLL               1
#define rc_morph_erode_disc_15x15_p_bin_SCORE                1.34e+08

#define rc_morph_dilate_disc_15x15_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_15x15_p_bin_UNROLL              4
#define rc_morph_dilate_disc_15x15_p_bin_SCORE               1.39e+08

#define rc_morph_erode_disc_17x17_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_17x17_p_bin_UNROLL               4
#define rc_morph_erode_disc_17x17_p_bin_SCORE                1.32e+08

#define rc_morph_dilate_disc_17x17_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_17x17_p_bin_UNROLL              4
#define rc_morph_dilate_disc_17x17_p_bin_SCORE               1.37e+08

#define rc_morph_erode_disc_19x19_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_19x19_p_bin_UNROLL               4
#define rc_morph_erode_disc_19x19_p_bin_SCORE                1.38e+08

#define rc_morph_dilate_disc_19x19_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_19x19_p_bin_UNROLL              4
#define rc_morph_dilate_disc_19x19_p_bin_SCORE               1.43e+08

#define rc_morph_erode_disc_25x25_p_bin_IMPL                 RC_IMPL_GEN
#define rc_morph_erode_disc_25x25_p_bin_UNROLL               1
#define rc_morph_erode_disc_25x25_p_bin_SCORE                8.80e+07

#define rc_morph_dilate_disc_25x25_p_bin_IMPL                RC_IMPL_GEN
#define rc_morph_dilate_disc_25x25_p_bin_UNROLL              1
#define rc_morph_dilate_disc_25x25_p_bin_SCORE               8.91e+07

#define rc_morph_hmt_golay_l_3x3_c48_r0_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r0_bin_UNROLL           4
#define rc_morph_hmt_golay_l_3x3_c48_r0_bin_SCORE            5.39e+08

#define rc_morph_hmt_golay_l_3x3_c48_r90_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r90_bin_UNROLL          2
#define rc_morph_hmt_golay_l_3x3_c48_r90_bin_SCORE           3.98e+08

#define rc_morph_hmt_golay_l_3x3_c48_r180_bin_IMPL           RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r180_bin_UNROLL         4
#define rc_morph_hmt_golay_l_3x3_c48_r180_bin_SCORE          5.21e+08

#define rc_morph_hmt_golay_l_3x3_c48_r270_bin_IMPL           RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c48_r270_bin_UNROLL         4
#define rc_morph_hmt_golay_l_3x3_c48_r270_bin_SCORE          4.07e+08

#define rc_morph_hmt_golay_l_3x3_c4_r45_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r45_bin_UNROLL           4
#define rc_morph_hmt_golay_l_3x3_c4_r45_bin_SCORE            6.67e+08

#define rc_morph_hmt_golay_l_3x3_c4_r135_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r135_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c4_r135_bin_SCORE           6.40e+08

#define rc_morph_hmt_golay_l_3x3_c4_r225_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r225_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c4_r225_bin_SCORE           6.41e+08

#define rc_morph_hmt_golay_l_3x3_c4_r315_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c4_r315_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c4_r315_bin_SCORE           6.80e+08

#define rc_morph_hmt_golay_l_3x3_c8_r45_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r45_bin_UNROLL           4
#define rc_morph_hmt_golay_l_3x3_c8_r45_bin_SCORE            6.45e+08

#define rc_morph_hmt_golay_l_3x3_c8_r135_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r135_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c8_r135_bin_SCORE           6.59e+08

#define rc_morph_hmt_golay_l_3x3_c8_r225_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r225_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c8_r225_bin_SCORE           6.65e+08

#define rc_morph_hmt_golay_l_3x3_c8_r315_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_l_3x3_c8_r315_bin_UNROLL          4
#define rc_morph_hmt_golay_l_3x3_c8_r315_bin_SCORE           6.46e+08

#define rc_morph_hmt_golay_e_3x3_c4_r0_bin_IMPL              RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r0_bin_UNROLL            4
#define rc_morph_hmt_golay_e_3x3_c4_r0_bin_SCORE             1.02e+09

#define rc_morph_hmt_golay_e_3x3_c4_r90_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r90_bin_UNROLL           4
#define rc_morph_hmt_golay_e_3x3_c4_r90_bin_SCORE            1.07e+09

#define rc_morph_hmt_golay_e_3x3_c4_r180_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r180_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c4_r180_bin_SCORE           9.85e+08

#define rc_morph_hmt_golay_e_3x3_c4_r270_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c4_r270_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c4_r270_bin_SCORE           1.12e+09

#define rc_morph_hmt_golay_e_3x3_c8_r0_bin_IMPL              RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r0_bin_UNROLL            4
#define rc_morph_hmt_golay_e_3x3_c8_r0_bin_SCORE             4.70e+08

#define rc_morph_hmt_golay_e_3x3_c8_r90_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r90_bin_UNROLL           4
#define rc_morph_hmt_golay_e_3x3_c8_r90_bin_SCORE            5.14e+08

#define rc_morph_hmt_golay_e_3x3_c8_r180_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r180_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r180_bin_SCORE           4.86e+08

#define rc_morph_hmt_golay_e_3x3_c8_r270_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r270_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r270_bin_SCORE           5.34e+08

#define rc_morph_hmt_golay_e_3x3_c8_r45_bin_IMPL             RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r45_bin_UNROLL           4
#define rc_morph_hmt_golay_e_3x3_c8_r45_bin_SCORE            5.19e+08

#define rc_morph_hmt_golay_e_3x3_c8_r135_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r135_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r135_bin_SCORE           4.61e+08

#define rc_morph_hmt_golay_e_3x3_c8_r225_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r225_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r225_bin_SCORE           5.34e+08

#define rc_morph_hmt_golay_e_3x3_c8_r315_bin_IMPL            RC_IMPL_GEN
#define rc_morph_hmt_golay_e_3x3_c8_r315_bin_UNROLL          4
#define rc_morph_hmt_golay_e_3x3_c8_r315_bin_SCORE           4.89e+08

#define rc_margin_horz_bin_IMPL                              RC_IMPL_SIMD
#define rc_margin_horz_bin_UNROLL                            2
#define rc_margin_horz_bin_SCORE                             4.40e+09

#define rc_margin_vert_bin_IMPL                              RC_IMPL_GEN
#define rc_margin_vert_bin_UNROLL                            4
#define rc_margin_vert_bin_SCORE                             4.32e+09

#define rc_cond_set_u8_IMPL                                  RC_IMPL_SIMD
#define rc_cond_set_u8_UNROLL                                4
#define rc_cond_set_u8_SCORE                                 1.50e+09

#define rc_cond_addc_u8_IMPL                                 RC_IMPL_SIMD
#define rc_cond_addc_u8_UNROLL                               4
#define rc_cond_addc_u8_SCORE                                1.51e+09

#define rc_cond_subc_u8_IMPL                                 RC_IMPL_SIMD
#define rc_cond_subc_u8_UNROLL                               4
#define rc_cond_subc_u8_SCORE                                1.50e+09

#define rc_cond_copy_u8_IMPL                                 RC_IMPL_SIMD
#define rc_cond_copy_u8_UNROLL                               4
#define rc_cond_copy_u8_SCORE                                1.48e+09

#define rc_cond_add_u8_IMPL                                  RC_IMPL_SIMD
#define rc_cond_add_u8_UNROLL                                4
#define rc_cond_add_u8_SCORE                                 1.49e+09

#endif /* RAPPTUNE_H */
